import { useState, useEffect } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'react-hot-toast';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { Checkbox } from '../ui/checkbox';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { FileCode, Loader2, Trash2 } from 'lucide-react';
import { useAuth } from '@/store/useAuth';
import appServices from '@/services/appServices';
import { useWorkbenchStore } from '@/stores/workbench-store';

interface CreateVariableModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  appTag?: string;
  appId?: string;
  variable?: any;
  onSuccess?: (variable: any) => void;
}

export default function CreateVariableModal({
  open,
  onOpenChange,
  appTag: _appTag, // No longer used - kept for backward compatibility
  appId,
  variable,
  onSuccess,
}: CreateVariableModalProps) {
  const { user, currentWorkspaceId } = useAuth();
  const queryClient = useQueryClient();
  const { updateTab, tabs } = useWorkbenchStore();

  const [formData, setFormData] = useState({
    key: '',
    description: '',
    type: 'string',
    minlength: '',
    maxlength: '',
    required: false,
  });

  // Populate form when editing
  useEffect(() => {
    if (variable) {
      setFormData({
        key: variable.key || '',
        description: variable.description || '',
        type: variable.type || 'string',
        minlength: variable.minlength?.toString() || '',
        maxlength: variable.maxlength?.toString() || '',
        required: variable.required || false,
      });
    } else {
      setFormData({
        key: '',
        description: '',
        type: 'string',
        minlength: '',
        maxlength: '',
        required: false,
      });
    }
  }, [variable, open]);

  const handleKeyChange = (value: string) => {
    // Sanitize key: replace invalid chars with underscore (keep original case)
    const sanitized = value.replace(/[^a-zA-Z0-9-_]/g, '_');

    // Auto-generate description only if description is empty or was auto-generated
    const shouldAutoGenerateDescription =
      !formData.description ||
      formData.description === `Variable for ${formData.key}`;

    setFormData({
      ...formData,
      key: sanitized,
      description: shouldAutoGenerateDescription
        ? (sanitized ? `Variable for ${sanitized}` : '')
        : formData.description
    });
  };

  const { mutate: createVariable, isPending: isCreating } = useMutation({
    mutationFn: async (data: typeof formData) => {
      if (!appId) throw new Error('App ID not found');
      if (!user?._id || !user?.public_key) throw new Error('User credentials not found');
      if (!currentWorkspaceId) throw new Error('Workspace ID not found');
      if (!data.key.trim()) throw new Error('Key is required');

      // Validate minLength < maxLength (unless maxLength is 0)
      const minLength = parseInt(data.minlength) || 0;
      const maxLength = parseInt(data.maxlength) || 0;
      
      if (maxLength !== 0 && minLength > maxLength) {
        throw new Error('Minimum length must be less than or equal to maximum length');
      }

      const payload: any = {
        component: 'variables',
        action: variable ? 'update' : 'create',
        workspace_id: currentWorkspaceId,
        user_id: user._id,
        public_key: user.public_key,
        key: data.key,
        type: data.type, // Keep lowercase as-is
        description: data.description || '',
        required: data.required || false,
      };

      // Add minlength/maxlength
      payload.minlength = minLength;
      payload.maxlength = maxLength;

      return appServices.updateApp({
        app_id: appId,
        user_id: user._id,
        public_key: user.public_key,
        payload,
      });
    },
    onSuccess: async () => {
      // Invalidate queries
      queryClient.invalidateQueries({ queryKey: ['app', appId] });
      queryClient.invalidateQueries({ queryKey: ['app-details-for-auth'] });

      // Fetch fresh app data and update the tab
      try {
        const response = await appServices.fetchApp({
          app_id: String(appId),
          user_id: user?._id || '',
          public_key: user?.public_key || '',
        });
        const updatedApp = response.data;

        // Find and update the app tab
        const appTab = tabs.find(t => t.type === 'app' && t.itemId === appId);
        if (appTab) {
          updateTab(appTab.id, { data: updatedApp });
        }
      } catch (error) {
        console.error('Failed to fetch updated app data:', error);
      }

      toast.success(variable ? 'Variable updated successfully!' : 'Variable created successfully!');
      onSuccess?.({});
      onOpenChange(false);
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.errors || error.message || 'Failed to create variable');
    },
  });

  const { mutate: deleteVariable, isPending: isDeleting } = useMutation({
    mutationFn: async () => {
      if (!appId) throw new Error('App ID not found');
      if (!user?._id || !user?.public_key) throw new Error('User credentials not found');
      if (!variable?.key) throw new Error('Variable key not found');

      const payload = {
        component: 'variables',
        action: 'delete',
        key: variable.key,
      };

      return appServices.updateApp({
        app_id: appId,
        user_id: user._id,
        public_key: user.public_key,
        payload,
      });
    },
    onSuccess: async () => {
      // Invalidate queries
      queryClient.invalidateQueries({ queryKey: ['app', appId] });
      queryClient.invalidateQueries({ queryKey: ['app-details-for-auth'] });

      // Fetch fresh app data and update the tab
      try {
        const response = await appServices.fetchApp({
          app_id: String(appId),
          user_id: user?._id || '',
          public_key: user?.public_key || '',
        });
        const updatedApp = response.data;

        // Find and update the app tab
        const appTab = tabs.find(t => t.type === 'app' && t.itemId === appId);
        if (appTab) {
          updateTab(appTab.id, { data: updatedApp });
        }
      } catch (error) {
        console.error('Failed to fetch updated app data:', error);
      }

      toast.success('Variable deleted successfully!');
      onOpenChange(false);
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.errors || error.message || 'Failed to delete variable');
    },
  });

  const handleSubmit = () => {
    if (!formData.key.trim()) {
      toast.error('Please enter a variable key');
      return;
    }

    // Validate minLength < maxLength (unless maxLength is 0)
    const minLength = parseInt(formData.minlength) || 0;
    const maxLength = parseInt(formData.maxlength) || 0;
    
    if (maxLength !== 0 && minLength > maxLength) {
      toast.error('Minimum length must be less than or equal to maximum length');
      return;
    }

    createVariable(formData);
  };

  const handleDelete = () => {
    if (window.confirm(`Are you sure you want to delete the variable "${variable?.key || formData.key}"?`)) {
      deleteVariable();
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px] max-h-[90vh] p-0 gap-0 flex flex-col overflow-hidden">
        {/* Header - Fixed */}
        <div className="px-6 pt-6 pb-4 border-b border-grey-400">
          <DialogHeader>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <FileCode className="h-5 w-5 text-primary" />
              </div>
              <div>
                <DialogTitle className='text-grey'>{variable ? 'Update Variable' : 'Create Variable'}</DialogTitle>
                <DialogDescription>
                  {variable ? 'Update the variable configuration' : 'Add a new variable to store dynamic configuration values'}
                </DialogDescription>
              </div>
            </div>
          </DialogHeader>
        </div>

        {/* Content - Scrollable */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-4">
          <div>
            <Label htmlFor="key" className="required">
              Variable Key
            </Label>
            <Input
              id="key"
              placeholder="e.g., API_KEY, DATABASE_URL"
              value={formData.key}
              onChange={(e) => handleKeyChange(e.target.value)}
              disabled={!!variable}
              className="mt-2"
              autoFocus={!variable}
            />
            <p className="text-xs text-grey-600 mt-1">
              A unique identifier for this variable
            </p>
          </div>

          <div>
            <Label htmlFor="description">
              Description
            </Label>
            <Textarea
              id="description"
              placeholder="Describe this variable..."
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              rows={3}
              className="mt-2"
            />
          </div>

          <div>
            <Label htmlFor="type">
              Variable Type
            </Label>
            <Select
              value={formData.type}
              onValueChange={(value) => setFormData({ ...formData, type: value })}
            >
              <SelectTrigger className="mt-2">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="string">STRING</SelectItem>
                <SelectItem value="nospaces_string">NO SPACES STRING</SelectItem>
                <SelectItem value="email_string">EMAIL STRING</SelectItem>
                <SelectItem value="number_string">NUMBER STRING</SelectItem>
                <SelectItem value="number">NUMBER (Integer)</SelectItem>
                <SelectItem value="float">FLOAT</SelectItem>
                <SelectItem value="double">DOUBLE</SelectItem>
                <SelectItem value="uuid">UUID</SelectItem>
                <SelectItem value="date_string">DATE STRING</SelectItem>
                <SelectItem value="date">DATE</SelectItem>
                <SelectItem value="boolean">BOOLEAN</SelectItem>
              </SelectContent>
            </Select>
            <p className="text-xs text-grey-600 mt-1">
              The data type for this variable
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="minlength">
                Minimum Length
              </Label>
              <Input
                id="minlength"
                type="number"
                min={0}
                placeholder="e.g., 5"
                value={formData.minlength}
                onChange={(e) => setFormData({ ...formData, minlength: e.target.value })}
                className="mt-2"
              />
            </div>

            <div>
              <Label htmlFor="maxlength">
                Maximum Length
              </Label>
              <Input
                id="maxlength"
                type="number"
                placeholder="e.g., 100"
                value={formData.maxlength}
                onChange={(e) => setFormData({ ...formData, maxlength: e.target.value })}
                className="mt-2"
              />
            </div>
          </div>

          <div className="flex items-center gap-3 rounded-lg border border-grey-400 p-4">
            <Checkbox
              id="required"
              checked={formData.required}
              onCheckedChange={(checked) => setFormData({ ...formData, required: checked as boolean })}
            />
            <div className="space-y-0.5">
              <Label htmlFor="required" className="text-sm font-medium cursor-pointer">
                Required
              </Label>
              <p className="text-xs text-grey-600">
                This variable must be provided for the app to function
              </p>
            </div>
          </div>
        </div>

        {/* Footer - Fixed */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-grey-400 bg-grey-50">
          {variable && (
            <Button
              variant="destructive"
              onClick={handleDelete}
              disabled={isDeleting || isCreating}
              className="gap-2"
            >
              {isDeleting ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Deleting...
                </>
              ) : (
                <>
                  <Trash2 className="h-4 w-4" />
                  Delete Variable
                </>
              )}
            </Button>
          )}
          <div className="flex gap-2 ml-auto">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isCreating || isDeleting}
            >
              Cancel
            </Button>
            <Button
              onClick={handleSubmit}
              disabled={isCreating || isDeleting}
              className="gap-2"
            >
              {isCreating ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  {variable ? 'Updating...' : 'Creating...'}
                </>
              ) : (
                <>
                  <FileCode className="h-4 w-4" />
                  {variable ? 'Update Variable' : 'Create Variable'}
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
