import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'react-hot-toast';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { Checkbox } from '../ui/checkbox';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { Settings2, Loader2 } from 'lucide-react';
import { useAuth } from '@/store/useAuth';
import { useDuctape } from '@/hooks/useDuctape';
import { DataFormats } from '@ductape/sdk/dist/types';

interface CreateAppEnvironmentModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  appTag?: string;
  appId?: string;
  onSuccess?: (environment: any) => void;
}

export default function CreateAppEnvironmentModal({
  open,
  onOpenChange,
  appTag,
  appId,
  onSuccess,
}: CreateAppEnvironmentModalProps) {
  const { user, currentWorkspaceId } = useAuth();
  const queryClient = useQueryClient();

  const [formData, setFormData] = useState({
    env_name: '',
    slug: '',
    description: '',
    active: true,
    base_url: '',
    request_type: DataFormats.JSON,
  });

  // Initialize Ductape SDK
  const ductape = useDuctape({
    workspace_id: currentWorkspaceId || '',
    user_id: user?._id || '',
    token: user?.auth_token || '',
    public_key: user?.public_key || '',
    type: 'app',
  }) as any;

  const handleNameChange = (value: string) => {
    // Auto-generate description only if description is empty or was auto-generated
    const shouldAutoGenerateDescription =
      !formData.description ||
      formData.description === `Environment for ${formData.env_name}`;

    // Auto-generate slug only if slug is empty or was auto-generated from the previous name
    const previousAutoSlug = formData.env_name
      .toLowerCase()
      .replace(/[^a-z]/g, '')
      .slice(0, 3)
      .padEnd(3, 'x');

    const shouldAutoGenerateSlug =
      !formData.slug ||
      formData.slug === previousAutoSlug;

    // Generate new slug from the current value
    const newSlug = value
      .toLowerCase()
      .replace(/[^a-z]/g, '')
      .slice(0, 3)
      .padEnd(3, 'x');

    setFormData({
      ...formData,
      env_name: value,
      description: shouldAutoGenerateDescription
        ? (value ? `Environment for ${value}` : '')
        : formData.description,
      slug: shouldAutoGenerateSlug ? (value ? newSlug : '') : formData.slug
    });
  };

  const handleSlugChange = (value: string) => {
    // Restrict to 3 characters exactly
    const sanitized = value.toLowerCase().slice(0, 3).replace(/[^a-z]/g, '');
    setFormData({ ...formData, slug: sanitized });
  };

  const handleAutoGenerateSlug = () => {
    if (!formData.env_name) {
      toast.error('Please enter an environment name first');
      return;
    }
    // Generate a 3-letter slug from the name
    const sanitized = formData.env_name
      .toLowerCase()
      .replace(/[^a-z]/g, '')
      .slice(0, 3)
      .padEnd(3, 'x'); // Pad with 'x' if less than 3 chars
    setFormData({ ...formData, slug: sanitized });
  };

  const { mutate: createEnvironment, isPending: isCreating } = useMutation({
    mutationFn: async (data: typeof formData) => {
      if (!ductape) throw new Error('App not initialized');
      if (!appTag) throw new Error('App tag not found');
      if (!data.base_url.trim()) throw new Error('Base URL is required');
      if (data.slug.length !== 3) throw new Error('Slug must be exactly 3 letters');

      await ductape.init(appTag);

      const payload = {
        env_name: data.env_name,
        slug: data.slug,
        description: data.description,
        active: data.active,
        base_url: data.base_url,
        request_type: data.request_type,
      };

      const environment = await ductape.environments.create(payload);
      return environment;
    },
    onSuccess: (environment) => {
      queryClient.invalidateQueries({ queryKey: ['app', appId] });
      toast.success('Environment created successfully!');
      onSuccess?.(environment);
      onOpenChange(false);
      // Reset form
      setFormData({
        env_name: '',
        slug: '',
        description: '',
        active: true,
        base_url: '',
        request_type: DataFormats.JSON,
      });
    },
    onError: (error: any) => {
      console.error('Error creating environment:', error);
      toast.error(error.message || 'Failed to create environment');
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.env_name.trim()) {
      toast.error('Please enter an environment name');
      return;
    }

    if (formData.slug.length !== 3) {
      toast.error('Slug must be exactly 3 letters');
      return;
    }

    if (!formData.base_url.trim()) {
      toast.error('Base URL is required');
      return;
    }

    createEnvironment(formData);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <Settings2 className="h-5 w-5 text-primary" />
            </div>
            <div>
              <DialogTitle className='text-grey'>Create Environment</DialogTitle>
              <DialogDescription>
                Add a new environment to organize deployment stages
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div>
            <Label htmlFor="env_name" className="required">
              Environment Name
            </Label>
            <Input
              id="env_name"
              placeholder="e.g., Production, Staging, Development"
              value={formData.env_name}
              onChange={(e) => handleNameChange(e.target.value)}
              className="mt-2"
              autoFocus
            />
            <p className="text-xs text-grey-600 mt-1">
              A descriptive name for this environment
            </p>
          </div>

          <div>
            <Label htmlFor="slug" className="required">
              Slug (3 letters)
            </Label>
            <div className="flex gap-2 mt-2">
              <Input
                id="slug"
                placeholder="e.g., prd, stg, dev"
                value={formData.slug}
                onChange={(e) => handleSlugChange(e.target.value)}
                maxLength={3}
                className="font-mono"
              />
              <Button
                type="button"
                variant="outline"
                onClick={handleAutoGenerateSlug}
                size="sm"
              >
                Auto-generate
              </Button>
            </div>
            <p className="text-xs text-grey-600 mt-1">
              Exactly 3 lowercase letters (e.g., prd, stg, dev)
            </p>
          </div>

          <div>
            <Label htmlFor="description">
              Description
            </Label>
            <Textarea
              id="description"
              placeholder="Describe this environment..."
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              rows={3}
              className="mt-2"
            />
          </div>

          <div>
            <Label htmlFor="base_url" className="required">
              Base URL
            </Label>
            <Input
              id="base_url"
              placeholder="https://api.example.com"
              value={formData.base_url}
              onChange={(e) => setFormData({ ...formData, base_url: e.target.value })}
              className="mt-2"
              type="url"
            />
            <p className="text-xs text-grey-600 mt-1">
              The base URL for this environment
            </p>
          </div>

          <div>
            <Label htmlFor="request_type">
              Request Type
            </Label>
            <Select
              value={formData.request_type}
              onValueChange={(value) => setFormData({ ...formData, request_type: value as DataFormats })}
            >
              <SelectTrigger className="mt-2">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={DataFormats.JSON}>JSON</SelectItem>
                <SelectItem value={DataFormats.URLENCODED}>URL Encoded</SelectItem>
                <SelectItem value={DataFormats.FORMDATA}>Form Data</SelectItem>
                <SelectItem value={DataFormats.SOAP}>SOAP</SelectItem>
                <SelectItem value={DataFormats.HTML}>HTML</SelectItem>
              </SelectContent>
            </Select>
            <p className="text-xs text-grey-600 mt-1">
              The data format for requests in this environment
            </p>
          </div>

          <div className="flex items-center gap-3 rounded-lg border border-grey-400 p-4">
            <Checkbox
              id="active"
              checked={formData.active}
              onCheckedChange={(checked) => setFormData({ ...formData, active: checked as boolean })}
            />
            <div className="space-y-0.5">
              <Label htmlFor="active" className="text-sm font-medium cursor-pointer">
                Active Status
              </Label>
              <p className="text-xs text-grey-600">
                Enable this environment for use
              </p>
            </div>
          </div>

          <div className="flex items-center justify-end gap-3 pt-4 border-t border-grey-400">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isCreating}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isCreating} className="gap-2">
              {isCreating ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Creating...
                </>
              ) : (
                <>
                  <Settings2 className="h-4 w-4" />
                  Create Environment
                </>
              )}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
    );
  }
