import { useState, useEffect } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'react-hot-toast';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { FileCode, Loader2, Trash2 } from 'lucide-react';
import { useAuth } from '@/store/useAuth';
import appServices from '@/services/appServices';
import { useWorkbenchStore } from '@/stores/workbench-store';

interface CreateConstantModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  appTag: string;
  appId: string;
  constant?: any;
  onSuccess?: (constant: any) => void;
}

export default function CreateConstantModal({
  open,
  onOpenChange,
  appTag: _appTag, // No longer used - kept for backward compatibility
  appId,
  constant,
  onSuccess,
}: CreateConstantModalProps) {
  const { user, currentWorkspaceId } = useAuth();
  const queryClient = useQueryClient();
  const { updateTab, tabs } = useWorkbenchStore();

  const [formData, setFormData] = useState({
    key: '',
    description: '',
    type: 'string',
    value: '',
  });

  // Populate form when editing
  useEffect(() => {
    if (constant) {
      setFormData({
        key: constant.key || '',
        description: constant.description || '',
        type: constant.type || 'string',
        value: constant.value || '',
      });
    } else {
      setFormData({
        key: '',
        description: '',
        type: 'string',
        value: '',
      });
    }
  }, [constant, open]);

  const handleKeyChange = (value: string) => {
    // Sanitize key: replace invalid chars with underscore (keep original case)
    const sanitized = value.replace(/[^a-zA-Z0-9-_]/g, '_');

    // Auto-generate description only if description is empty or was auto-generated
    const shouldAutoGenerateDescription =
      !formData.description ||
      formData.description === `Constant for ${formData.key}`;

    setFormData({
      ...formData,
      key: sanitized,
      description: shouldAutoGenerateDescription
        ? (sanitized ? `Constant for ${sanitized}` : '')
        : formData.description
    });
  };

  const handleValueChange = (value: string) => {
    let processedValue = value;

    // For nospaces_string: remove all spaces
    if (formData.type === 'nospaces_string') {
      processedValue = value.replace(/\s/g, '');
    }
    // For number and number_string: only allow digits, minus sign, and decimal point
    else if (formData.type === 'number' || formData.type === 'number_string') {
      // Only allow numbers, negative sign at start, and decimal point for integers we'll use the number input type
      // But for number_string, it's a string type, so we filter
      if (formData.type === 'number_string') {
        processedValue = value.replace(/[^0-9-.]/g, '');
        // Only allow one decimal point
        const parts = processedValue.split('.');
        if (parts.length > 2) {
          processedValue = parts[0] + '.' + parts.slice(1).join('');
        }
        // Only allow minus at the start
        if (processedValue.includes('-') && !processedValue.startsWith('-')) {
          processedValue = processedValue.replace(/-/g, '');
        }
      }
      // For regular number type, the input type="number" handles this
    }

    setFormData({ ...formData, value: processedValue });
  };

  const { mutate: createConstant, isPending: isCreating } = useMutation({
    mutationFn: async (data: typeof formData) => {
      if (!appId) throw new Error('App ID not found');
      if (!user?._id || !user?.public_key) throw new Error('User credentials not found');
      if (!currentWorkspaceId) throw new Error('Workspace ID not found');
      if (!data.key.trim()) throw new Error('Key is required');
      if (!data.value.trim()) throw new Error('Value is required');

      const payload: any = {
        component: 'constants',
        action: constant ? 'update' : 'create',
        workspace_id: currentWorkspaceId,
        user_id: user._id,
        public_key: user.public_key,
        key: data.key,
        type: data.type, // Keep lowercase as-is
        description: data.description || '',
        value: data.value,
      };

      return appServices.updateApp({
        app_id: appId,
        user_id: user._id,
        public_key: user.public_key,
        payload,
      });
    },
    onSuccess: async () => {
      // Invalidate queries
      queryClient.invalidateQueries({ queryKey: ['app', appId] });
      queryClient.invalidateQueries({ queryKey: ['app-details-for-auth'] });

      // Fetch fresh app data and update the tab
      try {
        const response = await appServices.fetchApp({
          app_id: appId,
          user_id: user?._id || '',
          public_key: user?.public_key || '',
        });
        const updatedApp = response.data;

        // Find and update the app tab
        const appTab = tabs.find(t => t.type === 'app' && t.itemId === appId);
        if (appTab) {
          updateTab(appTab.id, { data: updatedApp });
        }
      } catch (error) {
        console.error('Failed to fetch updated app data:', error);
      }

      toast.success(constant ? 'Constant updated successfully!' : 'Constant created successfully!');
      onSuccess?.({});
      onOpenChange(false);
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.errors || error.message || 'Failed to create constant');
    },
  });

  const { mutate: deleteConstant, isPending: isDeleting } = useMutation({
    mutationFn: async () => {
      if (!appId) throw new Error('App ID not found');
      if (!user?._id || !user?.public_key) throw new Error('User credentials not found');
      if (!constant?.key) throw new Error('Constant key not found');

      const payload = {
        component: 'constants',
        action: 'delete',
        key: constant.key,
      };

      return appServices.updateApp({
        app_id: appId,
        user_id: user._id,
        public_key: user.public_key,
        payload,
      });
    },
    onSuccess: async () => {
      // Invalidate queries
      queryClient.invalidateQueries({ queryKey: ['app', appId] });
      queryClient.invalidateQueries({ queryKey: ['app-details-for-auth'] });

      // Fetch fresh app data and update the tab
      try {
        const response = await appServices.fetchApp({
          app_id: appId,
          user_id: user?._id || '',
          public_key: user?.public_key || '',
        });
        const updatedApp = response.data;

        // Find and update the app tab
        const appTab = tabs.find(t => t.type === 'app' && t.itemId === appId);
        if (appTab) {
          updateTab(appTab.id, { data: updatedApp });
        }
      } catch (error) {
        console.error('Failed to fetch updated app data:', error);
      }

      toast.success('Constant deleted successfully!');
      onOpenChange(false);
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.errors || error.message || 'Failed to delete constant');
    },
  });

  const handleSubmit = () => {
    if (!formData.key.trim()) {
      toast.error('Please enter a constant key');
      return;
    }

    if (!formData.value.trim()) {
      toast.error('Please enter a constant value');
      return;
    }

    // Validate email format for email_string type
    if (formData.type === 'email_string') {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(formData.value)) {
        toast.error('Please enter a valid email address');
        return;
      }
    }

    createConstant(formData);
  };

  const handleDelete = () => {
    if (window.confirm(`Are you sure you want to delete the constant "${constant?.key || formData.key}"?`)) {
      deleteConstant();
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <FileCode className="h-5 w-5 text-primary" />
            </div>
            <div>
              <DialogTitle className='text-grey'>{constant ? 'Update Constant' : 'Create Constant'}</DialogTitle>
              <DialogDescription>
                {constant ? 'Update the constant configuration' : 'Add a new constant to store fixed configuration values'}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-4 mt-4">
          <div>
            <Label htmlFor="key" className="required">
              Constant Key
            </Label>
            <Input
              id="key"
              placeholder="e.g., API_VERSION, MAX_RETRIES"
              value={formData.key}
              onChange={(e) => handleKeyChange(e.target.value)}
              disabled={!!constant}
              className="mt-2"
              autoFocus={!constant}
            />
            <p className="text-xs text-grey-600 mt-1">
              A unique identifier for this constant
            </p>
          </div>

          <div>
            <Label htmlFor="description">
              Description
            </Label>
            <Textarea
              id="description"
              placeholder="Describe this constant..."
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              rows={3}
              className="mt-2"
            />
          </div>

          <div>
            <Label htmlFor="type">
              Constant Type
            </Label>
            <Select
              value={formData.type}
              onValueChange={(value) => setFormData({ ...formData, type: value, value: '' })}
            >
              <SelectTrigger className="mt-2">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="string">STRING</SelectItem>
                <SelectItem value="nospaces_string">NO SPACES STRING</SelectItem>
                <SelectItem value="email_string">EMAIL STRING</SelectItem>
                <SelectItem value="number_string">NUMBER STRING</SelectItem>
                <SelectItem value="number">NUMBER (Integer)</SelectItem>
                <SelectItem value="float">FLOAT</SelectItem>
                <SelectItem value="double">DOUBLE</SelectItem>
                <SelectItem value="uuid">UUID</SelectItem>
                <SelectItem value="date_string">DATE STRING</SelectItem>
                <SelectItem value="date">DATE</SelectItem>
                <SelectItem value="boolean">BOOLEAN</SelectItem>
              </SelectContent>
            </Select>
            <p className="text-xs text-grey-600 mt-1">
              The data type for this constant
            </p>
          </div>

          <div>
            <Label htmlFor="value" className="required">
              Value
            </Label>
            {formData.type === 'boolean' ? (
              <Select
                value={formData.value}
                onValueChange={(value) => setFormData({ ...formData, value })}
              >
                <SelectTrigger className="mt-2">
                  <SelectValue placeholder="Select boolean value" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="true">true</SelectItem>
                  <SelectItem value="false">false</SelectItem>
                </SelectContent>
              </Select>
            ) : (
              <Input
                id="value"
                type={
                  formData.type === 'number' || formData.type === 'float' || formData.type === 'double'
                    ? 'number'
                    : formData.type === 'email_string'
                    ? 'email'
                    : formData.type === 'date'
                    ? 'date'
                    : formData.type === 'date_string'
                    ? 'date'
                    : 'text'
                }
                placeholder={
                  formData.type === 'boolean'
                    ? 'true or false'
                    : formData.type === 'number' || formData.type === 'float' || formData.type === 'double'
                    ? 'Enter a number'
                    : formData.type === 'email_string'
                    ? 'Enter an email address'
                    : formData.type === 'date' || formData.type === 'date_string'
                    ? 'Select a date'
                    : formData.type === 'uuid'
                    ? 'Enter a UUID'
                    : formData.type === 'nospaces_string'
                    ? 'Enter text without spaces'
                    : 'Enter the constant value'
                }
                value={formData.value}
                onChange={(e) => handleValueChange(e.target.value)}
                className="mt-2"
                step={formData.type === 'float' || formData.type === 'double' ? 'any' : undefined}
                onKeyDown={
                  formData.type === 'number' || formData.type === 'number_string'
                    ? (e) => {
                        // Allow: backspace, delete, tab, escape, enter, and decimal point
                        if (
                          [8, 9, 27, 13, 46, 110, 190].indexOf(e.keyCode) !== -1 ||
                          // Allow: Ctrl+A, Ctrl+C, Ctrl+V, Ctrl+X
                          (e.keyCode === 65 && e.ctrlKey === true) ||
                          (e.keyCode === 67 && e.ctrlKey === true) ||
                          (e.keyCode === 86 && e.ctrlKey === true) ||
                          (e.keyCode === 88 && e.ctrlKey === true) ||
                          // Allow: home, end, left, right, down, up
                          (e.keyCode >= 35 && e.keyCode <= 40)
                        ) {
                          return;
                        }
                        // Ensure that it is a number and stop the keypress for number_string
                        if (
                          formData.type === 'number_string' &&
                          ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) &&
                          e.keyCode !== 189 // minus sign
                        ) {
                          e.preventDefault();
                        }
                      }
                    : undefined
                }
              />
            )}
            <p className="text-xs text-grey-600 mt-1">
              {formData.type === 'boolean'
                ? 'Select true or false'
                : formData.type === 'number' || formData.type === 'float' || formData.type === 'double'
                ? 'Enter a numeric value'
                : formData.type === 'email_string'
                ? 'Enter a valid email address'
                : formData.type === 'date' || formData.type === 'date_string'
                ? 'Select a date'
                : formData.type === 'uuid'
                ? 'Enter a valid UUID (e.g., 123e4567-e89b-12d3-a456-426614174000)'
                : formData.type === 'nospaces_string'
                ? 'Text without spaces'
                : 'The fixed value for this constant'}
            </p>
          </div>

          <div className="flex items-center justify-between pt-4 border-t border-grey-400">
            {constant && (
              <Button
                variant="destructive"
                onClick={handleDelete}
                disabled={isDeleting || isCreating}
                className="gap-2"
              >
                {isDeleting ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Deleting...
                  </>
                ) : (
                  <>
                    <Trash2 className="h-4 w-4" />
                    Delete Constant
                  </>
                )}
              </Button>
            )}
            <div className="flex gap-2 ml-auto">
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
                disabled={isCreating || isDeleting}
              >
                Cancel
              </Button>
              <Button
                onClick={handleSubmit}
                disabled={isCreating || isDeleting}
                className="gap-2"
              >
                {isCreating ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    {constant ? 'Updating...' : 'Creating...'}
                  </>
                ) : (
                  <>
                    <FileCode className="h-4 w-4" />
                    {constant ? 'Update Constant' : 'Create Constant'}
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
