import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Send, Plus, Trash2, Code, Globe, Hash, FileCode, Server, RotateCcw, BookOpen, X, List, Zap, ChevronDown, ChevronRight } from 'lucide-react';
import toast from 'react-hot-toast';
import { cn } from '@/lib/utils';
import { useAuth } from '@/store/useAuth';
import { reconstructPayloadFromSample, reconstructActionPayload } from '@/utils/payloadReconstruction';
import CodeSidebar from '@/components/CodeSidebar';

interface ActionViewTabContentProps {
  action: any;
}

interface KeyValue {
  key: string;
  value: string;
  description?: string;
  enabled: boolean;
}

interface ICustomEnv {
  slug: string;
  base_url: string;
  config?: Record<string, unknown>;
  active: boolean;
}

// Helper function to syntax highlight JSON
const syntaxHighlightJSON = (jsonString: any) => {
  try {
    const obj = typeof jsonString === 'string' ? JSON.parse(jsonString) : jsonString;
    const formatted = JSON.stringify(obj, null, 2);

    return formatted.replace(
      /("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g,
      (match) => {
        let cls = 'text-purple-600'; // numbers
        if (/^"/.test(match)) {
          if (/:$/.test(match)) {
            cls = 'text-blue-600 font-semibold'; // keys
          } else {
            cls = 'text-green-700'; // string values
          }
        } else if (/true|false/.test(match)) {
          cls = 'text-orange-600'; // boolean
        } else if (/null/.test(match)) {
          cls = 'text-red-600'; // null
        }
        return `<span class="${cls}">${match}</span>`;
      }
    );
  } catch (e) {
    return typeof jsonString === 'string' ? jsonString : JSON.stringify(jsonString, null, 2);
  }
};

export default function ActionViewTabContent({ action }: ActionViewTabContentProps) {
  const { user } = useAuth();

  // Persistent state key based on action identifier
  const stateKey = `action-view-state-${action?.appTag}-${action?.tag}`;

  // Load persisted state from localStorage - use a ref to ensure it's only loaded once
  const getPersistedState = () => {
    try {
      const saved = localStorage.getItem(stateKey);
      return saved ? JSON.parse(saved) : null;
    } catch {
      return null;
    }
  };

  // Use useState with initializer to ensure persisted state is only loaded once on mount
  const [initialPersistedState] = useState(() => getPersistedState());
  const persistedState = initialPersistedState;

  // ALL hooks must be called before any conditional returns
  // Form state matching the action data
  const [formData, setFormData] = useState({
    name: action?.name || action?.tag || '',
    tag: action?.tag || '',
    description: action?.description || '',
    method: action?.method || 'GET',
    request_type: 'JSON',
  });

  const handleNameChange = (value: string) => {
    // Auto-generate description only if description is empty or was auto-generated
    const shouldAutoGenerateDescription =
      !formData.description ||
      formData.description === `Action for ${formData.name}`;

    setFormData({
      ...formData,
      name: value,
      description: shouldAutoGenerateDescription
        ? (value ? `Action for ${value}` : '')
        : formData.description
    });
  };

  const [fullUrl, setFullUrl] = useState('');
  const [baseUrl, setBaseUrl] = useState(persistedState?.baseUrl || '');
  const [resource, setResource] = useState(action?.resource || '');
  const [params, setParams] = useState<KeyValue[]>(persistedState?.params || []);
  const [query, setQuery] = useState<KeyValue[]>(persistedState?.query || []);
  const [headers, setHeaders] = useState<KeyValue[]>(
    persistedState?.headers || [{ key: 'Content-Type', value: 'application/json', enabled: true }]
  );
  const [body, setBody] = useState(persistedState?.body || '');
  const [response, setResponse] = useState<any>(persistedState?.response || null);
  const [isLoadingRequest, setIsLoadingRequest] = useState(false);
  const [activeTab, setActiveTab] = useState(persistedState?.activeTab || 'params');

  // Custom envs that will be saved with the action (ICustomEnv[])
  const [customEnvs, setCustomEnvs] = useState<ICustomEnv[]>(persistedState?.customEnvs || []);

  // State to track which CustomEnv is being updated for highlighting
  const [updatingEnvSlugs, setUpdatingEnvSlugs] = useState<Set<string>>(new Set());

  // Environment modal state
  const [showEnvModal, setShowEnvModal] = useState(false);
  const [selectedEnvForModal, setSelectedEnvForModal] = useState<ICustomEnv | null>(null);
  const [editedEnvBaseUrl, setEditedEnvBaseUrl] = useState('');

  // Documentation sidebar state
  const [showDocsSidebar, setShowDocsSidebar] = useState<boolean>(false);
  const [selectedActionForDocs, setSelectedActionForDocs] = useState<any>(null);
  const [showBodyDataTable, setShowBodyDataTable] = useState<boolean>(false);
  const [showResponseDataTables, setShowResponseDataTables] = useState<Record<number, boolean>>({});

  // Code sidebar state
  const [showCodeSidebar, setShowCodeSidebar] = useState<boolean>(false);
  const [showDefaultValuesForm, setShowDefaultValuesForm] = useState<boolean>(false);
  const [defaultValues, setDefaultValues] = useState<Array<{ variable: string; valueSource: string; value: string }>>([]);

  // Collapsible details section state (collapsed by default)
  const [isDetailsExpanded, setIsDetailsExpanded] = useState<boolean>(false);

  // Use app data passed from parent component
  const app = {
    app_name: action?.appName,
    tag: action?.appTag,
    logo: action?.appLogo,
    status: action?.appStatus,
  };

  // Use environments passed from parent component
  const environments = action?.envs || [];

  // Initialize form data from action
  useEffect(() => {
    if (action) {
      setFormData({
        name: action.name || action.tag || '',
        tag: action.tag || '',
        description: action.description || '',
        method: action.method || 'GET',
        request_type: 'JSON',
      });
      setResource(action.resource || '');
    }
  }, [action]);

  // Initialize customEnvs from app environments (only if no persisted state)
  useEffect(() => {
    // Skip if we have persisted state
    if (persistedState) return;

    if (environments.length > 0 && customEnvs.length === 0) {
      // Find if any env is marked as active, otherwise default to first one
      const activeEnvIndex = environments.findIndex((env: any) => env.active);
      const defaultActiveIndex = activeEnvIndex >= 0 ? activeEnvIndex : 0;

      const envs = environments.map((env: any, index: number) => ({
        slug: env.slug,
        base_url: env.base_url || '',
        active: index === defaultActiveIndex,
      }));
      setCustomEnvs(envs);

      // Set the active environment's base URL
      const activeEnv = environments[defaultActiveIndex];
      if (activeEnv?.base_url) {
        setBaseUrl(activeEnv.base_url);
      }
    }
  }, [environments]);

  // Initialize params, query, headers from action data (only if no persisted state)
  useEffect(() => {
    // Skip initialization if we have persisted state
    if (persistedState) return;

    if (action) {
      // Initialize params (only simple types, arrays/objects are handled via reconstruction)
      if (action.params?.data) {
        const simpleParams = action.params.data.filter((param: any) => {
          const fieldType = param.type?.toLowerCase() || '';
          return fieldType !== 'array' &&
                 !fieldType.startsWith('array') &&
                 fieldType !== 'object' &&
                 fieldType !== 'json';
        });

        setParams(
          simpleParams.map((param: any) => ({
            key: param.key || '',
            value: param.default || param.defaultValue || '',
            description: param.description || '',
            enabled: true,
          }))
        );
      }

      // Initialize query (only simple types, arrays/objects are handled via reconstruction)
      if (action.query?.data) {
        const simpleQuery = action.query.data.filter((param: any) => {
          const fieldType = param.type?.toLowerCase() || '';
          return fieldType !== 'array' &&
                 !fieldType.startsWith('array') &&
                 fieldType !== 'object' &&
                 fieldType !== 'json';
        });

        setQuery(
          simpleQuery.map((param: any) => ({
            key: param.key || '',
            value: param.default || param.defaultValue || '',
            description: param.description || '',
            enabled: true,
          }))
        );
      }

      // Initialize headers (only simple types, arrays/objects are handled via reconstruction)
      if (action.headers?.data) {
        const simpleHeaders = action.headers.data.filter((header: any) => {
          const fieldType = header.type?.toLowerCase() || '';
          return fieldType !== 'array' &&
                 !fieldType.startsWith('array') &&
                 fieldType !== 'object' &&
                 fieldType !== 'json';
        });

        // Check if Content-Type already exists in action headers
        const hasContentType = simpleHeaders.some(
          (header: any) => header.key?.toLowerCase() === 'content-type'
        );

        const mappedHeaders = simpleHeaders.map((header: any) => ({
          key: header.key || '',
          value: header.sampleValue || '',
          description: header.description || '',
          enabled: true,
        }));

        // Only add default Content-Type if it's not already in the action headers
        setHeaders(
          hasContentType
            ? mappedHeaders
            : [{ key: 'Content-Type', value: 'application/json', enabled: true }, ...mappedHeaders]
        );
      }

      // Initialize body with reconstruction from sample data
      if (action.body) {
        let bodyContent: any = {};

        // Try to use the parsed data structure first (IParsedSample array)
        if (action.body.data && Array.isArray(action.body.data) && action.body.data.length > 0) {
          // Reconstruct the full body structure using sample data
          // The reconstruction function will use sampleValue from IParsedSample
          // and handle nested objects/arrays properly
          bodyContent = reconstructPayloadFromSample(
            action.body.data,
            {} // Empty user inputs - let it use sample values
          );
        }
        // Fallback to using the raw sample if data is not available
        else if (action.body.sample) {
          try {
            // If sample is a string, parse it
            bodyContent = typeof action.body.sample === 'string'
              ? JSON.parse(action.body.sample)
              : action.body.sample;
          } catch (e) {
            // If parsing fails, use as-is or empty object
            bodyContent = action.body.sample || {};
          }
        }

        setBody(JSON.stringify(bodyContent, null, 2));
      }
    }
  }, [action]);

  // Build full URL from base URL and resource
  useEffect(() => {
    if (baseUrl && resource) {
      // Use simple string concatenation to preserve template variables like {{baseVersion}}
      // The URL constructor would encode curly braces as %7B%7D
      const normalizedResource = resource.startsWith('/') ? resource : `/${resource}`;
      const normalizedBaseUrl = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;
      setFullUrl(`${normalizedBaseUrl}${normalizedResource}`);
    } else if (baseUrl) {
      // If only base URL is available, show it
      setFullUrl(baseUrl);
    } else if (resource) {
      // If only resource is available, show it
      setFullUrl(resource);
    }
  }, [baseUrl, resource]);

  // Auto-update all custom envs when base URL changes (not matching any existing env)
  useEffect(() => {
    if (baseUrl && customEnvs.length > 0) {
      const matchingEnv = customEnvs.find(e => e.base_url === baseUrl);

      // If base URL doesn't match any env, update all envs to this new base URL
      if (!matchingEnv) {
        // Highlight all envs being updated
        const envSlugs = customEnvs.map(env => env.slug);
        setUpdatingEnvSlugs(new Set(envSlugs));
        
        setCustomEnvs(prev => prev.map(env => ({
          ...env,
          base_url: baseUrl
        })));
        
        // Remove highlighting after a short delay
        setTimeout(() => {
          setUpdatingEnvSlugs(new Set());
        }, 1000);
      }
    }
  }, [baseUrl]);

  // Persist state to localStorage whenever relevant state changes
  useEffect(() => {
    const stateToSave = {
      activeTab,
      baseUrl,
      params,
      query,
      headers,
      body,
      response,
      customEnvs,
    };
    localStorage.setItem(stateKey, JSON.stringify(stateToSave));
  }, [stateKey, activeTab, baseUrl, params, query, headers, body, response, customEnvs]);

  const handleEnvSelect = (slug: string) => {
    // Highlight the env being updated
    setUpdatingEnvSlugs(prev => new Set(prev).add(slug));

    const env = customEnvs.find(e => e.slug === slug);
    if (env?.base_url) {
      setBaseUrl(env.base_url);
    }
    // Set this env as active
    setCustomEnvs(prev => prev.map(e => ({
      ...e,
      active: e.slug === slug
    })));

    // Remove highlighting after a short delay
    setTimeout(() => {
      setUpdatingEnvSlugs(prev => {
        const newSet = new Set(prev);
        newSet.delete(slug);
        return newSet;
      });
    }, 1000);
  };

  const handleOpenEnvModal = (env: ICustomEnv) => {
    setSelectedEnvForModal(env);
    setEditedEnvBaseUrl(env.base_url);
    setShowEnvModal(true);
  };

  const handleSaveEnvChanges = () => {
    if (!selectedEnvForModal) return;

    const slug = selectedEnvForModal.slug;

    // Update the env base URL
    setCustomEnvs(prev => prev.map(e => {
      if (e.slug === slug) {
        return { ...e, base_url: editedEnvBaseUrl };
      }
      return e;
    }));

    // If this is the active env, update the main base URL too
    if (selectedEnvForModal.active) {
      setBaseUrl(editedEnvBaseUrl);
    }

    toast.success('Environment updated');
    setShowEnvModal(false);
    setSelectedEnvForModal(null);
  };

  const handleSelectEnvFromModal = () => {
    if (!selectedEnvForModal) return;

    // Save changes first
    handleSaveEnvChanges();

    // Then select this env
    handleEnvSelect(selectedEnvForModal.slug);
  };

  const handleResetEnv = (slug: string) => {
    // Highlight the env being reset
    setUpdatingEnvSlugs(prev => new Set(prev).add(slug));
    
    const originalEnv = environments.find((e: any) => e.slug === slug);
    if (originalEnv) {
      setCustomEnvs(prev => prev.map(env => {
        if (env.slug === slug) {
          return {
            ...env,
            base_url: originalEnv.base_url || '',
          };
        }
        return env;
      }));

      // If this is the active env, update the main base URL too
      const env = customEnvs.find(e => e.slug === slug && e.active);
      if (env) {
        setBaseUrl(originalEnv.base_url || '');
      }

      toast.success('Environment reset to default');
      
      // Remove highlighting after a short delay
      setTimeout(() => {
        setUpdatingEnvSlugs(prev => {
          const newSet = new Set(prev);
          newSet.delete(slug);
          return newSet;
        });
      }, 1000);
    }
  };

  const addKeyValue = (
    setter: React.Dispatch<React.SetStateAction<KeyValue[]>>
  ) => {
    setter(prev => [...prev, { key: '', value: '', enabled: true }]);
  };

  const updateKeyValue = (
    index: number,
    field: keyof KeyValue,
    value: any,
    setter: React.Dispatch<React.SetStateAction<KeyValue[]>>
  ) => {
    setter(prev => {
      const updated = [...prev];
      updated[index] = { ...updated[index], [field]: value };
      return updated;
    });
  };

  const removeKeyValue = (
    index: number,
    setter: React.Dispatch<React.SetStateAction<KeyValue[]>>
  ) => {
    setter(prev => prev.filter((_, i) => i !== index));
  };

  const handleTest = async () => {
    if (!fullUrl) {
      toast.error('Please enter a valid URL');
      return;
    }

    setIsLoadingRequest(true);
    try {
      // Collect simple user inputs from UI
      const userQueryParams: Record<string, string> = {};
      query
        .filter((q) => q.enabled && q.key)
        .forEach((q) => {
          userQueryParams[q.key] = q.value;
        });

      const userHeaders: Record<string, string> = {};
      headers
        .filter((h) => h.enabled && h.key)
        .forEach((h) => {
          userHeaders[h.key] = h.value;
        });

      const userPathParams: Record<string, string> = {};
      params
        .filter((p) => p.enabled && p.key)
        .forEach((p) => {
          userPathParams[p.key] = p.value;
        });

      // Parse body
      let userBodyData: any = {};
      if (['POST', 'PUT', 'PATCH'].includes(formData.method) && body) {
        try {
          userBodyData = JSON.parse(body);
        } catch {
          userBodyData = body; // Keep as string if not valid JSON
        }
      }

      // Reconstruct the full payload using sample data from action
      // This merges simple user inputs with complex structures (arrays/objects) from samples
      const reconstructed = reconstructActionPayload(
        {
          params: action?.params,
          body: action?.body,
          query: action?.query,
          headers: action?.headers,
        },
        {
          params: userPathParams,
          body: userBodyData,
          query: userQueryParams,
          headers: userHeaders,
        }
      );

      const queryParams = reconstructed.query || userQueryParams;
      const requestHeaders = reconstructed.headers || userHeaders;
      const pathParams = reconstructed.params || userPathParams;
      const parsedBody = reconstructed.body || userBodyData;

      // Call backend proxy
      const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || 'https://api.ductape.app/';
      const proxyUrl = `${apiBaseUrl}apps/v1/test-action`;

      const res = await fetch(proxyUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${user?.auth_token}`,
          'x-user-id': user?._id || '',
          'x-workspace-id': '',
        },
        body: JSON.stringify({
          url: fullUrl,
          method: formData.method,
          headers: requestHeaders,
          query: Object.keys(queryParams).length > 0 ? queryParams : undefined,
          params: Object.keys(pathParams).length > 0 ? pathParams : undefined,
          body: parsedBody,
        }),
      });

      const responseData = await res.json();

      // Extract metadata and actual response data
      const { _meta, data: actualData } = responseData;

      if (res.ok) {
        setResponse({
          status: _meta?.status || res.status,
          statusText: _meta?.statusText || res.statusText,
          headers: _meta?.headers || {},
          data: actualData, // The actual API response (can be array or object)
          time: _meta?.time,
          size: _meta?.size,
        });
        toast.success('Request completed');
      } else {
        // Handle error response
        setResponse({
          status: _meta?.status || res.status,
          statusText: _meta?.statusText || res.statusText,
          headers: _meta?.headers || {},
          data: actualData, // The actual API error response
          error: _meta?.error || 'Request failed',
          time: _meta?.time,
          size: _meta?.size,
        });
        toast.error(_meta?.error || 'Request failed');
      }

      setActiveTab('response'); // Auto-switch to response tab
    } catch (error: any) {
      toast.error(`Request failed: ${error.message}`);
      setResponse({
        error: error.message,
        status: 0,
        statusText: 'Network Error',
      });
      setActiveTab('response'); // Auto-switch to response tab even on error
    } finally {
      setIsLoadingRequest(false);
    }
  };


  const getMethodColor = (method: string) => {
    switch (method) {
      case 'GET':
        return 'bg-green/10 text-green';
      case 'POST':
        return 'bg-blue/10 text-blue';
      case 'PUT':
        return 'bg-orange-500/10 text-orange-500';
      case 'PATCH':
        return 'bg-purple-500/10 text-purple-500';
      case 'DELETE':
        return 'bg-red/10 text-red';
      default:
        return 'bg-grey-400 text-grey';
    }
  };

  // Default values management functions
  const addDefaultValue = () => {
    setDefaultValues(prev => [...prev, { variable: '', valueSource: '', value: '' }]);
  };

  const handleSetDefaultValues = () => {
    setShowDefaultValuesForm(prev => {
      const newValue = !prev;
      if (newValue && defaultValues.length === 0) {
        addDefaultValue();
      }
      return newValue;
    });
  };

  const removeDefaultValue = (index: number) => {
    setDefaultValues(prev => prev.filter((_, i) => i !== index));
  };

  const updateDefaultValue = (index: number, field: 'variable' | 'valueSource' | 'value', value: string) => {
    setDefaultValues(prev => prev.map((item, i) =>
      i === index ? { ...item, [field]: value } : item
    ));
  };

  const getValueForSource = (sourceType: string, selectedValue: string) => {
    switch (sourceType) {
      case 'default':
        return '$Default';
      case 'input':
        return selectedValue;
      default:
        return selectedValue;
    }
  };

  // Get available variables from params, query, headers, body
  const availableVariables = [
    ...params.filter(p => p.key).map(p => ({ label: p.key, value: p.key, type: 'param' })),
    ...query.filter(q => q.key).map(q => ({ label: q.key, value: q.key, type: 'query' })),
    ...headers.filter(h => h.key).map(h => ({ label: h.key, value: h.key, type: 'header' })),
  ];

  const availableValueSources = [
    { label: 'Default', value: 'default' },
    { label: 'Input', value: 'input' }
  ];

  // Auth-related headers that should be included in code generation
  const AUTH_RELATED_HEADERS: string[] = [
    'authorization', 'proxy-authorization', 'www-authenticate', 'proxy-authenticate',
    'x-api-key', 'api-key', 'apikey', 'x-auth-key', 'x-app-key', 'x-application-key',
    'app-key', 'application-key', 'x-service-key', 'service-key',
    'x-auth-token', 'x-access-token', 'x-bearer-token', 'x-refresh-token', 'x-id-token',
    'x-jwt', 'x-jwt-token', 'bearer', 'token', 'access-token', 'refresh-token',
    'id-token', 'jwt', 'jwt-token',
    'x-secret-key', 'x-client-secret', 'x-private-key', 'x-secret', 'x-app-secret',
    'x-application-secret', 'client-secret', 'secret-key', 'private-key', 'secret',
    'app-secret', 'application-secret',
    'cookie', 'set-cookie', 'x-session-id', 'x-session-token', 'session-id',
    'session-token', 'sessionid', 'sid',
    'x-csrf-token', 'x-xsrf-token', 'csrf-token', 'xsrf-token', 'x-csrf', 'x-xsrf', 'csrf', 'xsrf',
    'x-oauth-token', 'x-oauth-signature', 'x-client-id', 'client-id', 'clientid',
    'x-consumer-key', 'consumer-key', 'x-consumer-secret', 'consumer-secret',
    'oauth-token', 'oauth-signature', 'x-oauth-consumer-key', 'x-oauth-consumer-secret',
    'x-signature', 'x-hmac-signature', 'x-request-signature', 'x-hub-signature',
    'x-hub-signature-256', 'signature', 'hmac-signature', 'request-signature',
    'stripe-signature', 'x-stripe-signature',
    'x-amz-security-token', 'x-amz-date', 'x-amz-content-sha256',
    'x-ms-authorization-auxiliary', 'x-ms-identity-principal-id',
    'x-goog-api-key', 'x-goog-authenticated-user-id',
    'x-firebase-appcheck',
    'x-credential', 'x-credentials', 'x-user-token', 'x-account-token',
    'x-tenant-id', 'x-tenant-token', 'x-workspace-key', 'x-workspace-secret',
    'x-project-key', 'x-project-secret',
    'x-username', 'x-password', 'x-user', 'x-pass', 'username', 'password',
    'x-license-key', 'license-key', 'x-subscription-key', 'subscription-key',
    'idempotency-key', 'x-idempotency-key', 'x-request-id',
  ];

  // Helper function to flatten body object for flatInput format using ':' notation
  const flattenObject = (obj: any, prefix: string = ''): Array<{ key: string; value: string }> => {
    const result: Array<{ key: string; value: string }> = [];

    for (const [key, value] of Object.entries(obj)) {
      const newKey = prefix ? `${prefix}:${key}` : key;

      if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
        result.push(...flattenObject(value, newKey));
      } else {
        result.push({ key: newKey, value: typeof value === 'string' ? value : JSON.stringify(value) });
      }
    }

    return result;
  };

  // Generate SDK code sections for CodeSidebar component
  const generateCodeSections = (language: string, env?: string) => {
    const appTag = action?.appTag || 'your-app-tag';
    const actionTag = formData.tag || action?.tag || 'action-tag';
    const envSlug = env || customEnvs.find(e => e.active)?.slug || 'production';

    // Prepare enabled params, query for code examples
    const enabledParams = params.filter(p => p.enabled && p.key);
    const enabledQuery = query.filter(q => q.enabled && q.key);
    // Only include auth-related headers, filter out non-critical ones like Content-Type, Accept, etc.
    const enabledHeaders = headers.filter(h =>
      h.enabled && h.key && AUTH_RELATED_HEADERS.includes(h.key.toLowerCase())
    );

    // Parse body if available
    let bodyObj: any = null;
    if (['POST', 'PUT', 'PATCH'].includes(formData.method) && body) {
      try {
        bodyObj = JSON.parse(body);
      } catch {
        bodyObj = body;
      }
    }

    // Helper function to get value with default override
    const getParamValue = (key: string, value: string) => {
      const defaultValue = defaultValues.find(dv => dv.variable === key);
      if (defaultValue && defaultValue.valueSource) {
        const formattedValue = getValueForSource(defaultValue.valueSource, defaultValue.value);
        return formattedValue;
      }
      return value || `{{${key}}}`;
    };

    // Generate flatInput format - only add prefix when there's a key conflict
    const generateFlatInput = (indent: string = '    ') => {
      const flatEntries: string[] = [];

      // Collect all keys to detect conflicts
      const paramKeys = enabledParams.map(p => p.key);
      const queryKeys = enabledQuery.map(q => q.key);
      const headerKeys = enabledHeaders.map(h => h.key);
      const bodyKeys = bodyObj && typeof bodyObj === 'object'
        ? flattenObject(bodyObj, '').map(({ key }) => key.split(':')[0])
        : [];

      // Check if a key exists in multiple parts of the request
      const hasConflict = (key: string, source: 'params' | 'query' | 'headers' | 'body') => {
        const otherSources = {
          params: [...queryKeys, ...headerKeys, ...bodyKeys],
          query: [...paramKeys, ...headerKeys, ...bodyKeys],
          headers: [...paramKeys, ...queryKeys, ...bodyKeys],
          body: [...paramKeys, ...queryKeys, ...headerKeys],
        };
        return otherSources[source].includes(key);
      };

      // Flatten params - add 'params:' prefix only if key conflicts
      enabledParams.forEach(p => {
        const keyWithPrefix = hasConflict(p.key, 'params') ? `params:${p.key}` : p.key;
        flatEntries.push(`${indent}'${keyWithPrefix}': '${getParamValue(p.key, p.value)}'`);
      });

      // Flatten query - add 'query:' prefix only if key conflicts
      enabledQuery.forEach(q => {
        const keyWithPrefix = hasConflict(q.key, 'query') ? `query:${q.key}` : q.key;
        flatEntries.push(`${indent}'${keyWithPrefix}': '${getParamValue(q.key, q.value)}'`);
      });

      // Flatten headers - add 'headers:' prefix only if key conflicts
      enabledHeaders.forEach(h => {
        const keyWithPrefix = hasConflict(h.key, 'headers') ? `headers:${h.key}` : h.key;
        flatEntries.push(`${indent}'${keyWithPrefix}': '${getParamValue(h.key, h.value)}'`);
      });

      // Flatten body - add 'body:' prefix only if key conflicts
      if (bodyObj && typeof bodyObj === 'object') {
        const flatBody = flattenObject(bodyObj, '');
        flatBody.forEach(({ key, value }) => {
          const rootKey = key.split(':')[0];
          const keyWithPrefix = hasConflict(rootKey, 'body') ? `body:${key}` : key;
          flatEntries.push(`${indent}'${keyWithPrefix}': '${value}'`);
        });
      } else if (bodyObj) {
        const keyWithPrefix = hasConflict('body', 'body') ? 'body:body' : 'body';
        flatEntries.push(`${indent}'${keyWithPrefix}': '${bodyObj}'`);
      }

      return flatEntries.join(',\n');
    };

    switch (language) {
      case 'javascript':
        return [
          {
            title: 'Init Ductape',
            code: `const Ductape = require("@ductape/sdk")

const ductape = new Ductape({
  workspace_id: 'your-workspace-id',
  user_id: 'your-user-id',
  private_key: 'your-private-key'
});`
          },
          {
            title: 'Input',
            code: `const payload = {
  env: '${envSlug}',
  app: '${appTag}',
  action: '${actionTag}',
  input: {
${generateFlatInput('    ')}
  },
  retries: 3
};`
          },
          {
            title: 'Execute',
            code: `const result = await ductape.action.run(payload);
console.log('Action result:', result);`
          }
        ];

      case 'typescript':
        return [
          {
            title: 'Init Ductape',
            code: `import Ductape from "@ductape/sdk"

const ductape = new Ductape({
  workspace_id: 'your-workspace-id',
  user_id: 'your-user-id',
  private_key: 'your-private-key'
});`
          },
          {
            title: 'Input',
            code: `const payload = {
  env: '${envSlug}',
  app: '${appTag}',
  action: '${actionTag}',
  input: {
${generateFlatInput('    ')}
  },
  retries: 3
};`
          },
          {
            title: 'Execute',
            code: `const result = await ductape.action.run(payload);
console.log('Action result:', result);`
          }
        ];

      case 'python':
        return [
          {
            title: 'Init Ductape',
            code: `from ductape import Ductape

ductape = Ductape(
    workspace_id='your-workspace-id',
    user_id='your-user-id',
    private_key='your-private-key'
)`
          },
          {
            title: 'Input',
            code: `payload_data = {
    'env': '${envSlug}',
    'app': '${appTag}',
    'action': '${actionTag}',
    'input': {
${generateFlatInput('        ')}
    },
    'retries': 3
}`
          },
          {
            title: 'Execute',
            code: `result = ductape.apps.run(payload_data)
print('Action result:', result)`
          }
        ];

      case 'java':
        return [
          {
            title: 'Init Ductape',
            code: `import com.ductape.sdk.Ductape;
import com.ductape.sdk.models.*;

Ductape ductape = new Ductape.Builder()
    .workspaceId("your-workspace-id")
    .userId("your-user-id")
    .privateKey("your-private-key")
    .build();`
          },
          {
            title: 'Input',
            code: `Map<String, Object> input = new HashMap<>();
${enabledParams.length > 0 ? `
Map<String, Object> params = new HashMap<>();
${enabledParams.map(p => `params.put("${p.key}", "${getParamValue(p.key, p.value)}");`).join('\n')}
input.put("params", params);
` : ''}${enabledQuery.length > 0 ? `
Map<String, Object> query = new HashMap<>();
${enabledQuery.map(q => `query.put("${q.key}", "${getParamValue(q.key, q.value)}");`).join('\n')}
input.put("query", query);
` : ''}${enabledHeaders.length > 0 ? `
Map<String, Object> headers = new HashMap<>();
${enabledHeaders.map(h => `headers.put("${h.key}", "${getParamValue(h.key, h.value)}");`).join('\n')}
input.put("headers", headers);
` : ''}${bodyObj ? `
input.put("body", ${typeof bodyObj === 'string' ? `"${bodyObj}"` : JSON.stringify(bodyObj)});
` : ''}
ActionRequest request = new ActionRequest.Builder()
    .env("${envSlug}")
    .app("${appTag}")
    .event("${actionTag}")
    .input(input)
    .retries(3)
    .build();`
          },
          {
            title: 'Execute',
            code: `ActionResponse result = ductape.apps().run(request);
System.out.println("Action result: " + result);`
          }
        ];

      case 'ruby':
        return [
          {
            title: 'Init Ductape',
            code: `require 'ductape'

ductape = Ductape::Client.new(
  workspace_id: 'your-workspace-id',
  user_id: 'your-user-id',
  private_key: 'your-private-key'
)`
          },
          {
            title: 'Input',
            code: `payload = {
  env: '${envSlug}',
  app: '${appTag}',
  event: '${actionTag}',
  input: {${enabledParams.length > 0 ? `
    params: {
${enabledParams.map(p => `      ${p.key}: '${getParamValue(p.key, p.value)}'`).join(',\n')}
    },` : ''}${enabledQuery.length > 0 ? `
    query: {
${enabledQuery.map(q => `      ${q.key}: '${getParamValue(q.key, q.value)}'`).join(',\n')}
    },` : ''}${enabledHeaders.length > 0 ? `
    headers: {
${enabledHeaders.map(h => `      ${h.key}: '${getParamValue(h.key, h.value)}'`).join(',\n')}
    },` : ''}${bodyObj ? `
    body: ${typeof bodyObj === 'string' ? `'${bodyObj}'` : JSON.stringify(bodyObj, null, 4).split('\n').map((line, i) => i === 0 ? line : `    ${line}`).join('\n')},` : ''}
  },
  retries: 3
}`
          },
          {
            title: 'Execute',
            code: `result = ductape.apps.run(payload)
puts "Action result: #{result}"`
          }
        ];

      case 'php':
        return [
          {
            title: 'Init Ductape',
            code: `<?php
require_once 'vendor/autoload.php';

use Ductape\\Client;

$ductape = new Client([
    'workspace_id' => 'your-workspace-id',
    'user_id' => 'your-user-id',
    'private_key' => 'your-private-key'
]);`
          },
          {
            title: 'Input',
            code: `$payload = [
    'env' => '${envSlug}',
    'app' => '${appTag}',
    'event' => '${actionTag}',
    'input' => [${enabledParams.length > 0 ? `
        'params' => [
${enabledParams.map(p => `            '${p.key}' => '${getParamValue(p.key, p.value)}'`).join(',\n')}
        ],` : ''}${enabledQuery.length > 0 ? `
        'query' => [
${enabledQuery.map(q => `            '${q.key}' => '${getParamValue(q.key, q.value)}'`).join(',\n')}
        ],` : ''}${enabledHeaders.length > 0 ? `
        'headers' => [
${enabledHeaders.map(h => `            '${h.key}' => '${getParamValue(h.key, h.value)}'`).join(',\n')}
        ],` : ''}${bodyObj ? `
        'body' => ${typeof bodyObj === 'string' ? `'${bodyObj}'` : JSON.stringify(bodyObj, null, 4).split('\n').map((line, i) => i === 0 ? line : `        ${line}`).join('\n')},` : ''}
    ],
    'retries' => 3
];`
          },
          {
            title: 'Execute',
            code: `$result = $ductape->apps->run($payload);
echo "Action result: " . json_encode($result);`
          }
        ];

      case 'kotlin':
        return [
          {
            title: 'Init Ductape',
            code: `import com.ductape.sdk.Ductape
import com.ductape.sdk.models.*

val ductape = Ductape(
    workspaceId = "your-workspace-id",
    userId = "your-user-id",
    privateKey = "your-private-key"
)`
          },
          {
            title: 'Input',
            code: `val input = buildMap {
${enabledParams.length > 0 ? `    put("params", mapOf(
${enabledParams.map(p => `        "${p.key}" to "${getParamValue(p.key, p.value)}"`).join(',\n')}
    ))
` : ''}${enabledQuery.length > 0 ? `    put("query", mapOf(
${enabledQuery.map(q => `        "${q.key}" to "${getParamValue(q.key, q.value)}"`).join(',\n')}
    ))
` : ''}${enabledHeaders.length > 0 ? `    put("headers", mapOf(
${enabledHeaders.map(h => `        "${h.key}" to "${getParamValue(h.key, h.value)}"`).join(',\n')}
    ))
` : ''}${bodyObj ? `    put("body", ${typeof bodyObj === 'string' ? `"${bodyObj}"` : JSON.stringify(bodyObj)})
` : ''}}

val request = ActionRequest(
    env = "${envSlug}",
    app = "${appTag}",
    event = "${actionTag}",
    input = input,
    retries = 3
)`
          },
          {
            title: 'Execute',
            code: `val result = ductape.apps.run(request)
println("Action result: $result")`
          }
        ];

      case 'go':
        return [
          {
            title: 'Init Ductape',
            code: `package main

import (
    "github.com/ductape/ductape-go"
)

client := ductape.NewClient(&ductape.Config{
    WorkspaceID: "your-workspace-id",
    UserID:      "your-user-id",
    PrivateKey:  "your-private-key",
})`
          },
          {
            title: 'Input',
            code: `input := map[string]interface{}{${enabledParams.length > 0 ? `
    "params": map[string]interface{}{
${enabledParams.map(p => `        "${p.key}": "${getParamValue(p.key, p.value)}",`).join('\n')}
    },` : ''}${enabledQuery.length > 0 ? `
    "query": map[string]interface{}{
${enabledQuery.map(q => `        "${q.key}": "${getParamValue(q.key, q.value)}",`).join('\n')}
    },` : ''}${enabledHeaders.length > 0 ? `
    "headers": map[string]interface{}{
${enabledHeaders.map(h => `        "${h.key}": "${getParamValue(h.key, h.value)}",`).join('\n')}
    },` : ''}${bodyObj ? `
    "body": ${typeof bodyObj === 'string' ? `"${bodyObj}"` : JSON.stringify(bodyObj)},` : ''}
}

request := &ductape.ActionRequest{
    Env:     "${envSlug}",
    App:     "${appTag}",
    Event:   "${actionTag}",
    Input:   input,
    Retries: 3,
}`
          },
          {
            title: 'Execute',
            code: `result, err := client.Apps.Run(request)
if err != nil {
    log.Fatal(err)
}
fmt.Printf("Action result: %v\\n", result)`
          }
        ];

      case 'csharp':
        return [
          {
            title: 'Init Ductape',
            code: `using Ductape.Sdk;

var ductape = new DuctapeClient(new DuctapeConfig
{
    WorkspaceId = "your-workspace-id",
    UserId = "your-user-id",
    PrivateKey = "your-private-key"
});`
          },
          {
            title: 'Input',
            code: `var input = new Dictionary<string, object>
{${enabledParams.length > 0 ? `
    ["params"] = new Dictionary<string, object>
    {
${enabledParams.map(p => `        ["${p.key}"] = "${getParamValue(p.key, p.value)}",`).join('\n')}
    },` : ''}${enabledQuery.length > 0 ? `
    ["query"] = new Dictionary<string, object>
    {
${enabledQuery.map(q => `        ["${q.key}"] = "${getParamValue(q.key, q.value)}",`).join('\n')}
    },` : ''}${enabledHeaders.length > 0 ? `
    ["headers"] = new Dictionary<string, object>
    {
${enabledHeaders.map(h => `        ["${h.key}"] = "${getParamValue(h.key, h.value)}",`).join('\n')}
    },` : ''}${bodyObj ? `
    ["body"] = ${typeof bodyObj === 'string' ? `"${bodyObj}"` : JSON.stringify(bodyObj)},` : ''}
};

var request = new ActionRequest
{
    Env = "${envSlug}",
    App = "${appTag}",
    Event = "${actionTag}",
    Input = input,
    Retries = 3
};`
          },
          {
            title: 'Execute',
            code: `var result = await ductape.Action.RunAsync(request);
Console.WriteLine($"Action result: {result}");`
          }
        ];

      case 'rust':
        return [
          {
            title: 'Init Ductape',
            code: `use ductape_sdk::Ductape;
use std::collections::HashMap;

let ductape = Ductape::new(
    "your-workspace-id",
    "your-user-id",
    "your-private-key"
)?;`
          },
          {
            title: 'Input',
            code: `let mut input: HashMap<String, serde_json::Value> = HashMap::new();
${enabledParams.length > 0 ? `
let mut params: HashMap<String, serde_json::Value> = HashMap::new();
${enabledParams.map(p => `params.insert("${p.key}".to_string(), serde_json::json!("${getParamValue(p.key, p.value)}"));`).join('\n')}
input.insert("params".to_string(), serde_json::json!(params));
` : ''}${enabledQuery.length > 0 ? `
let mut query: HashMap<String, serde_json::Value> = HashMap::new();
${enabledQuery.map(q => `query.insert("${q.key}".to_string(), serde_json::json!("${getParamValue(q.key, q.value)}"));`).join('\n')}
input.insert("query".to_string(), serde_json::json!(query));
` : ''}${enabledHeaders.length > 0 ? `
let mut headers: HashMap<String, serde_json::Value> = HashMap::new();
${enabledHeaders.map(h => `headers.insert("${h.key}".to_string(), serde_json::json!("${getParamValue(h.key, h.value)}"));`).join('\n')}
input.insert("headers".to_string(), serde_json::json!(headers));
` : ''}${bodyObj ? `
input.insert("body".to_string(), serde_json::json!(${typeof bodyObj === 'string' ? `"${bodyObj}"` : JSON.stringify(bodyObj)}));
` : ''}
let request = ActionRequest {
    env: "${envSlug}".to_string(),
    app: "${appTag}".to_string(),
    event: "${actionTag}".to_string(),
    input,
    retries: 3,
};`
          },
          {
            title: 'Execute',
            code: `let result = ductape.apps.run(&request)?;
println!("Action result: {:?}", result);`
          }
        ];

      default:
        return [];
    }
  };

  // Show error if action data is incomplete
  if (!action?.name && !action?.tag) {
    return (
      <div className="h-full flex items-center justify-center bg-grey-100">
        <div className="text-center">
          <Zap className="h-12 w-12 text-grey-400 mx-auto mb-3" />
          <p className="text-grey-600 mb-2">Incomplete action data</p>
          <p className="text-grey-500 text-sm mb-4">
            This tab was restored from an older session with incomplete data.
          </p>
          <p className="text-grey-500 text-sm">
            Please close this tab and reopen the action from your product to reload it.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full overflow-hidden bg-grey-100 flex flex-col relative">
      {/* Top Section - Collapsible Action Details */}
      <div className="bg-white border-b border-grey-400 flex-shrink-0">
        {/* Header Bar - Always Visible */}
        <div className="px-4 py-3 flex items-center gap-3">
          {/* Collapse Toggle */}
          <button
            onClick={() => setIsDetailsExpanded(!isDetailsExpanded)}
            className="p-1 hover:bg-grey-100 rounded transition-colors"
          >
            {isDetailsExpanded ? (
              <ChevronDown className="h-4 w-4 text-grey-600" />
            ) : (
              <ChevronRight className="h-4 w-4 text-grey-600" />
            )}
          </button>

          {/* Method Badge */}
          <span className={cn('px-2 py-1 rounded text-xs font-bold', getMethodColor(formData.method))}>
            {formData.method}
          </span>

          {/* Action Name */}
          <h2 className="text-lg font-semibold text-grey truncate flex-1">
            {formData.name || formData.tag || 'Unnamed Action'}
          </h2>

          {/* Tag Badge */}
          <span className="text-xs text-grey-600 bg-grey-100 px-2 py-1 rounded font-mono hidden sm:inline">
            {formData.tag}
          </span>

          {/* Action Buttons */}
          <div className="flex gap-2">
            <Button
              onClick={() => {
                setSelectedActionForDocs(action);
                setShowDocsSidebar(true);
                setShowCodeSidebar(false);
              }}
              size="sm"
              variant="outline"
              className="h-8 px-3 text-xs"
            >
              <BookOpen className="w-3 h-3 mr-1" />
              <span className="hidden sm:inline">Docs</span>
            </Button>
            <Button
              onClick={() => {
                setShowCodeSidebar(true);
                setShowDocsSidebar(false);
              }}
              size="sm"
              variant="outline"
              className="h-8 px-3 text-xs"
            >
              <Code className="w-3 h-3 mr-1" />
              <span className="hidden sm:inline">Code</span>
            </Button>
          </div>
        </div>

        {/* Collapsible Details Section */}
        {isDetailsExpanded && (
          <div className="px-4 pb-4 space-y-4 border-t border-grey-200 pt-4">
            {/* Name and Description */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label className="text-sm font-medium text-grey-700 mb-1.5 block">Action Name</Label>
                <Input
                  placeholder="Action Name"
                  value={formData.name}
                  onChange={(e) => handleNameChange(e.target.value)}
                  className="h-9"
                />
              </div>
              <div>
                <Label className="text-sm font-medium text-grey-700 mb-1.5 block">Tag</Label>
                <Input
                  value={formData.tag}
                  readOnly
                  className="h-9 bg-grey-50 font-mono text-sm"
                />
              </div>
            </div>

            <div>
              <Label className="text-sm font-medium text-grey-700 mb-1.5 block">Description</Label>
              <Textarea
                placeholder="Description (optional)"
                value={formData.description}
                onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                className="text-sm resize-none"
                rows={2}
              />
            </div>

            {/* App Context - Compact */}
            {app?.app_name && (
              <div className="flex items-center gap-3 p-3 bg-grey-50 rounded-lg border border-grey-200">
                <div className="w-8 h-8 rounded-lg bg-green/10 flex items-center justify-center text-green text-xs font-semibold flex-shrink-0">
                  {app?.logo ? (
                    <img
                      src={app?.logo}
                      alt={app?.app_name}
                      className="w-full h-full rounded-lg object-cover"
                    />
                  ) : (
                    app?.app_name?.split(' ')
                      .map((word: string) => word[0])
                      .join('')
                      .toUpperCase()
                      .slice(0, 2)
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-grey truncate">{app?.app_name}</p>
                  <p className="text-xs text-grey-500 truncate">{app?.tag}</p>
                </div>
                {app?.status && (
                  <span className={cn(
                    'px-2 py-0.5 rounded text-xs font-medium',
                    app?.status === 'active' ? 'bg-green/10 text-green' : 'bg-grey-200 text-grey-600'
                  )}>
                    {app?.status}
                  </span>
                )}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Main Content Area - Vertical Layout */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* URL & Environment Bar */}
        <div className="bg-white border-b border-grey-400 p-4 flex-shrink-0">
          <div className="flex flex-col lg:flex-row gap-3">
            {/* Method + Send Button */}
            <div className="flex items-center gap-2">
              <Select
                value={formData.method}
                onValueChange={(value) => setFormData(prev => ({ ...prev, method: value }))}
              >
                <SelectTrigger className="w-24">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map(method => (
                    <SelectItem key={method} value={method}>
                      <span className={cn('px-2 py-0.5 rounded text-xs font-bold', getMethodColor(method))}>
                        {method}
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>

              <Button
                onClick={handleTest}
                disabled={isLoadingRequest || !fullUrl || !baseUrl}
                className="bg-primary text-white hover:bg-primary/90"
                size="sm"
              >
                <Send className="h-4 w-4 mr-1" />
                {isLoadingRequest ? 'Sending...' : 'Send'}
              </Button>
            </div>

            {/* URL Display */}
            <div className="flex-1">
              <Input
                placeholder={baseUrl ? "Full URL" : "Select an environment to see full URL"}
                value={fullUrl}
                readOnly
                className="font-mono text-sm bg-grey-50 dark:bg-transparent h-9"
              />
            </div>

            {/* Environment Selector */}
            {environments.length > 0 && (
              <div className="flex items-center gap-2">
                <Label className="text-xs text-grey-600 whitespace-nowrap">Env:</Label>
                <div className="flex gap-1">
                  {customEnvs.map((env) => {
                    const originalEnv = environments.find((e: any) => e.slug === env.slug);
                    const isUpdating = updatingEnvSlugs.has(env.slug);

                    return (
                      <button
                        key={env.slug}
                        onClick={() => handleEnvSelect(env.slug)}
                        className={cn(
                          'px-3 py-1.5 rounded text-xs font-medium transition-all border',
                          isUpdating && 'animate-pulse',
                          env.active
                            ? 'bg-primary text-white border-primary'
                            : 'bg-transparent text-grey-700 border-grey-300 hover:border-primary hover:text-primary'
                        )}
                      >
                        {originalEnv?.env_name || env.slug}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
          </div>

          {/* Resource Path - Compact */}
          <div className="mt-3 flex items-center gap-2">
            <Label className="text-xs text-grey-600 flex items-center gap-1 whitespace-nowrap">
              <Hash className="h-3 w-3" />
              Resource:
            </Label>
            <Input
              placeholder="/api/v1/endpoint"
              value={resource}
              onChange={(e) => setResource(e.target.value)}
              className="font-mono text-xs h-8 flex-1"
            />
          </div>

          {!baseUrl && (
            <div className="mt-2 text-xs text-amber-600 bg-amber-50 border border-amber-200 rounded px-3 py-1.5">
              Select an environment to enable the Send button
            </div>
          )}
        </div>

        {/* Request/Response Tabs */}
        <div className="flex-1 flex flex-col overflow-hidden min-h-0">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col min-h-0">
          <div className="border-b border-grey-400 bg-white px-4 lg:px-6 flex-shrink-0">
            <TabsList className="w-full justify-start rounded-none bg-transparent p-0 h-auto overflow-x-auto">
              <TabsTrigger
                value="params"
                className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-2.5 lg:px-3.5 py-2.5 text-xs lg:text-sm whitespace-nowrap gap-1.5"
              >
                Params
                {(params.length > 0 || query.length > 0) && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-primary/10 text-primary font-medium">
                    {params.length + query.length}
                  </span>
                )}
              </TabsTrigger>
              <TabsTrigger
                value="headers"
                className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-2.5 lg:px-3.5 py-2.5 text-xs lg:text-sm whitespace-nowrap gap-1.5"
              >
                Headers
                {headers.length > 0 && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-primary/10 text-primary font-medium">
                    {headers.length}
                  </span>
                )}
              </TabsTrigger>
              {['POST', 'PUT', 'PATCH'].includes(formData.method) && (
                <TabsTrigger
                  value="body"
                  className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-2.5 lg:px-3.5 py-2.5 text-xs lg:text-sm whitespace-nowrap gap-1.5"
                >
                  Body
                  {body && (
                    <span className="w-1.5 h-1.5 rounded-full bg-green" />
                  )}
                </TabsTrigger>
              )}
              <TabsTrigger
                value="response"
                className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-2.5 lg:px-3.5 py-2.5 text-xs lg:text-sm whitespace-nowrap gap-1.5"
                disabled={!response}
              >
                Response
                {response?.status && (
                  <span className={cn(
                    'text-[10px] px-1.5 py-0.5 rounded-full',
                    response.status >= 200 && response.status < 300
                      ? 'bg-green/10 text-green'
                      : 'bg-red/10 text-red'
                  )}>
                    {response.status}
                  </span>
                )}
              </TabsTrigger>
            </TabsList>
          </div>

          <div className="flex-1 min-h-0 overflow-y-auto">
            <TabsContent value="params" className="p-4 lg:p-6 space-y-6 m-0">
              {/* Query Parameters Section */}
              <div className="bg-white rounded-lg border border-grey-400 shadow-sm overflow-hidden">
                <div className="px-4 py-3 flex items-center justify-between border-b border-grey-400">
                  <h3 className="text-sm font-semibold text-grey flex items-center gap-2">
                    <Hash className="h-4 w-4 text-primary" />
                    Query Parameters
                  </h3>
                  <Button
                    onClick={() => addKeyValue(setQuery)}
                    variant="outline"
                    size="sm"
                    className="gap-2"
                  >
                    <Plus className="h-4 w-4" />
                    Add
                  </Button>
                </div>
                <div className="p-4">
                  {query.length === 0 ? (
                    <div className="text-center py-8">
                      <div className="w-12 h-12 rounded-full bg-grey-100 flex items-center justify-center mx-auto mb-3">
                        <Hash className="h-6 w-6 text-grey-400" />
                      </div>
                      <p className="text-grey-600 font-medium mb-1">No query parameters</p>
                      <p className="text-sm text-grey-500">Add query parameters to your request</p>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {query.map((item, index) => (
                        <div
                          key={index}
                          className="p-3 rounded-lg border border-grey-400 hover:border-primary transition-colors"
                        >
                          <div className="flex gap-3 items-center">
                            <input
                              type="checkbox"
                              checked={item.enabled}
                              onChange={(e) => updateKeyValue(index, 'enabled', e.target.checked, setQuery)}
                              className="w-4 h-4 rounded border-grey-400"
                            />
                            <Input
                              placeholder="Key"
                              value={item.key}
                              onChange={(e) => updateKeyValue(index, 'key', e.target.value, setQuery)}
                              className="flex-1 h-9"
                            />
                            <Input
                              placeholder="Value"
                              value={item.value}
                              onChange={(e) => updateKeyValue(index, 'value', e.target.value, setQuery)}
                              className="flex-1 h-9"
                            />
                            <Button
                              onClick={() => removeKeyValue(index, setQuery)}
                              variant="ghost"
                              size="sm"
                              className="text-grey-400 hover:text-red hover:bg-red/10"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              {/* Path Parameters Section */}
              <div className="bg-white rounded-lg border border-grey-400 shadow-sm overflow-hidden">
                <div className="px-4 py-3 flex items-center justify-between border-b border-grey-400">
                  <h3 className="text-sm font-semibold text-grey flex items-center gap-2">
                    <Server className="h-4 w-4 text-primary" />
                    Path Parameters
                  </h3>
                  <Button
                    onClick={() => addKeyValue(setParams)}
                    variant="outline"
                    size="sm"
                    className="gap-2"
                  >
                    <Plus className="h-4 w-4" />
                    Add
                  </Button>
                </div>
                <div className="p-4">
                  {params.length === 0 ? (
                    <div className="text-center py-8">
                      <div className="w-12 h-12 rounded-full bg-grey-100 flex items-center justify-center mx-auto mb-3">
                        <Server className="h-6 w-6 text-grey-400" />
                      </div>
                      <p className="text-grey-600 font-medium mb-1">No path parameters</p>
                      <p className="text-sm text-grey-500">Add path parameters like :id or :slug</p>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {params.map((item, index) => (
                        <div
                          key={index}
                          className="p-3 rounded-lg border border-grey-400 hover:border-primary transition-colors"
                        >
                          <div className="flex gap-3 items-center">
                            <input
                              type="checkbox"
                              checked={item.enabled}
                              onChange={(e) => updateKeyValue(index, 'enabled', e.target.checked, setParams)}
                              className="w-4 h-4 rounded border-grey-400"
                            />
                            <Input
                              placeholder="Key"
                              value={item.key}
                              onChange={(e) => updateKeyValue(index, 'key', e.target.value, setParams)}
                              className="flex-1 h-9"
                            />
                            <Input
                              placeholder="Value"
                              value={item.value}
                              onChange={(e) => updateKeyValue(index, 'value', e.target.value, setParams)}
                              className="flex-1 h-9"
                            />
                            <Button
                              onClick={() => removeKeyValue(index, setParams)}
                              variant="ghost"
                              size="sm"
                              className="text-grey-400 hover:text-red hover:bg-red/10"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </TabsContent>

            <TabsContent value="headers" className="p-4 lg:p-6 m-0">
              <div className="bg-white rounded-lg border border-grey-400 shadow-sm overflow-hidden">
                <div className="px-4 py-3 flex items-center justify-between border-b border-grey-400">
                  <h3 className="text-sm font-semibold text-grey flex items-center gap-2">
                    <Globe className="h-4 w-4 text-primary" />
                    Request Headers
                  </h3>
                  <Button
                    onClick={() => addKeyValue(setHeaders)}
                    variant="outline"
                    size="sm"
                    className="gap-2"
                  >
                    <Plus className="h-4 w-4" />
                    Add
                  </Button>
                </div>
                <div className="p-4">
                  {headers.length === 0 ? (
                    <div className="text-center py-8">
                      <div className="w-12 h-12 rounded-full bg-grey-100 flex items-center justify-center mx-auto mb-3">
                        <Globe className="h-6 w-6 text-grey-400" />
                      </div>
                      <p className="text-grey-600 font-medium mb-1">No headers defined</p>
                      <p className="text-sm text-grey-500">Add custom headers to your request</p>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {headers.map((item, index) => (
                        <div
                          key={index}
                          className="p-3 rounded-lg border border-grey-400 hover:border-primary transition-colors"
                        >
                          <div className="flex gap-3 items-center">
                            <input
                              type="checkbox"
                              checked={item.enabled}
                              onChange={(e) => updateKeyValue(index, 'enabled', e.target.checked, setHeaders)}
                              className="w-4 h-4 rounded border-grey-400"
                            />
                            <Input
                              placeholder="Header-Name"
                              value={item.key}
                              onChange={(e) => updateKeyValue(index, 'key', e.target.value, setHeaders)}
                              className="flex-1 h-9"
                            />
                            <Input
                              placeholder="Value"
                              value={item.value}
                              onChange={(e) => updateKeyValue(index, 'value', e.target.value, setHeaders)}
                              className="flex-1 h-9"
                            />
                            <Button
                              onClick={() => removeKeyValue(index, setHeaders)}
                              variant="ghost"
                              size="sm"
                              className="text-grey-400 hover:text-red hover:bg-red/10"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </TabsContent>

            {['POST', 'PUT', 'PATCH'].includes(formData.method) && (
              <TabsContent value="body" className="p-4 lg:p-6 m-0 flex-1 flex flex-col min-h-0">
                <div className="bg-white rounded-lg border border-grey-400 shadow-sm overflow-hidden flex-1 flex flex-col min-h-0">
                  <div className="px-4 py-3 flex items-center justify-between border-b border-grey-400 flex-shrink-0">
                    <h3 className="text-sm font-semibold text-grey flex items-center gap-2">
                      <FileCode className="h-4 w-4 text-primary" />
                      Request Body
                    </h3>
                  </div>
                  <div className="p-4 flex-1 min-h-0 h-full">
                    <Textarea
                      placeholder='{\n  "key": "value"\n}'
                      value={body}
                      onChange={(e) => setBody(e.target.value)}
                      className="font-mono text-sm border-grey-400 resize-none min-h-[250px] w-full"
                    />
                  </div>
                </div>
              </TabsContent>
            )}

            <TabsContent value="response" className="m-0 flex flex-col">
              {!response ? (
                <div className="flex items-center justify-center h-full text-grey-600">
                  <div className="text-center">
                    <p className="text-lg mb-2">No response yet</p>
                    <p className="text-sm">Send a request to see the response</p>
                  </div>
                </div>
              ) : (
                <div className="h-full flex flex-col overflow-hidden">
                  {response.status && (
                    <div className="flex-shrink-0 flex items-center gap-2 p-3 mx-6 mt-6 bg-grey-100 rounded-lg border border-grey-400">
                      <span className="text-sm font-medium text-grey-600">Status:</span>
                      <span className={cn(
                        'px-3 py-1 rounded text-xs font-bold',
                        response.status >= 200 && response.status < 300
                          ? 'bg-green/10 text-green border border-green/20'
                          : response.status >= 400
                          ? 'bg-red/10 text-red border border-red/20'
                          : 'bg-grey-400 text-grey'
                      )}>
                        {response.status} {response.statusText}
                      </span>
                      {response.time !== undefined && (
                        <>
                          <span className="text-grey-300 mx-2">|</span>
                          <span className="text-sm font-medium text-grey-600">Time:</span>
                          <span className="text-sm text-grey-700">{response.time}ms</span>
                        </>
                      )}
                      {response.size !== undefined && (
                        <>
                          <span className="text-grey-300 mx-2">|</span>
                          <span className="text-sm font-medium text-grey-600">Size:</span>
                          <span className="text-sm text-grey-700">{response.size} bytes</span>
                        </>
                      )}
                    </div>
                  )}
                  <div className="flex-1 flex flex-col min-h-0 px-6 pb-6 pt-4">
                    <div className="flex items-center justify-between mb-2 flex-shrink-0">
                      <Label className="text-sm font-medium text-grey-600">Response Body</Label>
                      <Button
                        onClick={() => {
                          try {
                            const jsonString = JSON.stringify(response.data || response, null, 2);
                            navigator.clipboard.writeText(jsonString);
                            toast.success('Response copied to clipboard');
                          } catch (e) {
                            toast.error('Failed to copy response');
                          }
                        }}
                        variant="outline"
                        size="sm"
                        className="gap-2"
                      >
                        <Code className="h-4 w-4" />
                        Copy
                      </Button>
                    </div>
                    <div className="flex-1 bg-white rounded-lg border border-grey-400 p-4 overflow-auto font-mono text-sm">
                      <pre
                        className="text-grey-800"
                        style={{
                          whiteSpace: 'pre-wrap',
                          wordBreak: 'break-word',
                        }}
                        dangerouslySetInnerHTML={{
                          __html: syntaxHighlightJSON(response.data || response)
                        }}
                      />
                    </div>
                  </div>
                </div>
              )}
            </TabsContent>
          </div>
        </Tabs>
        </div>
      </div>

      {/* Documentation Sidebar */}
      {showDocsSidebar && selectedActionForDocs && (
        <div className="fixed top-0 right-0 h-full w-[500px] bg-white shadow-2xl border-l border-grey-300 z-50 overflow-y-auto">
          <div className="sticky top-0 bg-white border-b border-grey-300 p-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-grey flex items-center gap-2">
              <BookOpen className="w-5 h-5" />
              Action Documentation
            </h3>
            <Button
              onClick={() => {
                setShowDocsSidebar(false);
                setSelectedActionForDocs(null);
              }}
              variant="ghost"
              size="sm"
            >
              <X className="w-4 h-4" />
            </Button>
          </div>

          <div className="p-4 space-y-6">
            {/* Action Details */}
            <div>
              <h4 className="text-lg font-bold text-grey mb-2">{selectedActionForDocs.name || selectedActionForDocs.tag}</h4>
              {selectedActionForDocs.tag && (
                <span className="text-xs px-2 py-1 bg-primary/15 text-primary rounded font-mono">
                  {selectedActionForDocs.tag}
                </span>
              )}
            </div>

            {/* Method */}
            {selectedActionForDocs.method && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-1 block">Method</Label>
                <span className={cn(
                  'px-3 py-1 rounded text-xs font-bold inline-block',
                  selectedActionForDocs.method === 'GET' && 'bg-green/10 text-green',
                  selectedActionForDocs.method === 'POST' && 'bg-blue/10 text-blue',
                  selectedActionForDocs.method === 'PUT' && 'bg-orange-500/10 text-orange-500',
                  selectedActionForDocs.method === 'PATCH' && 'bg-purple-500/10 text-purple-500',
                  selectedActionForDocs.method === 'DELETE' && 'bg-red/10 text-red',
                )}>
                  {selectedActionForDocs.method}
                </span>
              </div>
            )}

            {/* Description */}
            {selectedActionForDocs.description && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-1 block">Description</Label>
                <p className="text-sm text-grey">{selectedActionForDocs.description}</p>
              </div>
            )}

            {/* Endpoint/Resource */}
            {selectedActionForDocs.resource && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-1 block">Endpoint</Label>
                <code className="text-xs bg-grey-100 text-grey px-2 py-1 rounded border border-grey-400 font-mono block overflow-x-auto">
                  {selectedActionForDocs.resource}
                </code>
              </div>
            )}

            {/* Request Type */}
            {selectedActionForDocs.request_type && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-1 block">Request Type</Label>
                <span className="text-xs px-2 py-1 bg-grey-100 text-grey rounded border border-grey-400">
                  {selectedActionForDocs.request_type}
                </span>
              </div>
            )}

            {/* Path Parameters */}
            {selectedActionForDocs.params?.data && selectedActionForDocs.params.data.length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-2 block">Path Parameters</Label>
                <div className="border border-grey-400 rounded overflow-hidden">
                  <Table className="text-xs">
                    <TableHeader>
                      <TableRow className="bg-grey-100">
                        <TableHead className="font-semibold text-grey">Key</TableHead>
                        <TableHead className="font-semibold text-grey">Type</TableHead>
                        <TableHead className="font-semibold text-grey">Description</TableHead>
                        <TableHead className="font-semibold text-grey">Required</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {selectedActionForDocs.params.data.map((param: any, index: number) => (
                        <TableRow key={index}>
                          <TableCell className="font-mono text-grey">{param.key}</TableCell>
                          <TableCell>
                            <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                              {param.type || 'string'}
                            </span>
                          </TableCell>
                          <TableCell className="text-grey">{param.description || '-'}</TableCell>
                          <TableCell>
                            <span className={cn(
                              'px-2 py-0.5 rounded text-xs font-medium',
                              param.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey'
                            )}>
                              {param.required ? 'Yes' : 'No'}
                            </span>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            {/* Query Parameters */}
            {selectedActionForDocs.query?.data && selectedActionForDocs.query.data.length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-2 block">Query Parameters</Label>
                <div className="border border-grey-400 rounded overflow-hidden">
                  <Table className="text-xs">
                    <TableHeader>
                      <TableRow className="bg-grey-100">
                        <TableHead className="font-semibold text-grey">Key</TableHead>
                        <TableHead className="font-semibold text-grey">Type</TableHead>
                        <TableHead className="font-semibold text-grey">Description</TableHead>
                        <TableHead className="font-semibold text-grey">Required</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {selectedActionForDocs.query.data.map((param: any, index: number) => (
                        <TableRow key={index}>
                          <TableCell className="font-mono text-grey">{param.key}</TableCell>
                          <TableCell>
                            <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                              {param.type || 'string'}
                            </span>
                          </TableCell>
                          <TableCell className="text-grey">{param.description || '-'}</TableCell>
                          <TableCell>
                            <span className={cn(
                              'px-2 py-0.5 rounded text-xs font-medium',
                              param.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey'
                            )}>
                              {param.required ? 'Yes' : 'No'}
                            </span>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            {/* Headers */}
            {selectedActionForDocs.headers?.data && selectedActionForDocs.headers.data.length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-2 block">Headers</Label>
                <div className="border border-grey-400 rounded overflow-hidden">
                  <Table className="text-xs">
                    <TableHeader>
                      <TableRow className="bg-grey-100">
                        <TableHead className="font-semibold text-grey">Key</TableHead>
                        <TableHead className="font-semibold text-grey">Description</TableHead>
                        <TableHead className="font-semibold text-grey">Required</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {selectedActionForDocs.headers.data.map((header: any, index: number) => (
                        <TableRow key={index}>
                          <TableCell className="font-mono text-grey">{header.key}</TableCell>
                          <TableCell className="text-grey">{header.description || '-'}</TableCell>
                          <TableCell>
                            <span className={cn(
                              'px-2 py-0.5 rounded text-xs font-medium',
                              header.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey'
                            )}>
                              {header.required ? 'Yes' : 'No'}
                            </span>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            {/* Request Body */}
            {selectedActionForDocs.body?.sample && (
              <div>
                <div className="flex items-center justify-between mb-2">
                  <Label className="text-sm font-semibold text-grey">Request Body</Label>
                  {selectedActionForDocs.body?.data && selectedActionForDocs.body.data.length > 0 && (
                    <Button
                      onClick={() => setShowBodyDataTable(!showBodyDataTable)}
                      variant="outline"
                      size="sm"
                      className="h-7 px-2 text-xs"
                    >
                      <List className="w-3 h-3 mr-1" />
                      {showBodyDataTable ? 'Show Sample' : 'Show Data'}
                    </Button>
                  )}
                </div>
                {!showBodyDataTable ? (
                  <div className="bg-grey-100 rounded border border-grey-400 p-3">
                    <pre className="text-xs font-mono overflow-x-auto text-grey">
                      {(() => {
                        try {
                          const sample = selectedActionForDocs.body.sample;
                          if (typeof sample === 'string') {
                            try {
                              const parsed = JSON.parse(sample);
                              return JSON.stringify(parsed, null, 2);
                            } catch {
                              return sample;
                            }
                          }
                          return JSON.stringify(sample, null, 2);
                        } catch {
                          return selectedActionForDocs.body.sample;
                        }
                      })()}
                    </pre>
                  </div>
                ) : (
                  <div className="border border-grey-400 rounded overflow-hidden">
                    <Table className="text-xs">
                      <TableHeader>
                        <TableRow className="bg-grey-100">
                          <TableHead className="font-semibold text-grey">Key</TableHead>
                          <TableHead className="font-semibold text-grey">Type</TableHead>
                          <TableHead className="font-semibold text-grey">Description</TableHead>
                          <TableHead className="font-semibold text-grey">Length</TableHead>
                          <TableHead className="font-semibold text-grey">Required</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {selectedActionForDocs.body.data.map((field: any, index: number) => (
                          <TableRow key={index}>
                            <TableCell className="font-mono text-grey">{field.key}</TableCell>
                            <TableCell>
                              <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                                {field.type || 'string'}
                              </span>
                            </TableCell>
                            <TableCell className="text-grey">{field.description || '-'}</TableCell>
                            <TableCell className="text-grey text-xs">
                              {field.minLength || field.maxLength ? (
                                <span>
                                  {field.minLength && `min: ${field.minLength}`}
                                  {field.minLength && field.maxLength && ', '}
                                  {field.maxLength && `max: ${field.maxLength}`}
                                </span>
                              ) : '-'}
                            </TableCell>
                            <TableCell>
                              <span className={cn(
                                'px-2 py-0.5 rounded text-xs font-medium',
                                field.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey'
                              )}>
                                {field.required ? 'Yes' : 'No'}
                              </span>
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                )}
              </div>
            )}

            {/* Responses */}
            {selectedActionForDocs.responses && selectedActionForDocs.responses.filter((r: any) => r.success === true).length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey mb-2 block">Responses</Label>
                <div className="space-y-3">
                  {selectedActionForDocs.responses.filter((r: any) => r.success === true).map((response: any, index: number) => (
                    <div key={index} className="border border-grey-400 rounded-lg overflow-hidden">
                      <div className="bg-grey-100 px-3 py-2 flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className={cn(
                            'px-2 py-1 rounded text-xs font-medium',
                            response.status >= 200 && response.status < 300 ? 'bg-green/10 text-green' : 'bg-grey-100 text-grey'
                          )}>
                            {response.status}
                          </span>
                          <span className="text-xs text-grey">{response.message || 'Success'}</span>
                        </div>
                        {response.body?.data && response.body.data.length > 0 && (
                          <Button
                            onClick={() => setShowResponseDataTables(prev => ({ ...prev, [index]: !prev[index] }))}
                            variant="outline"
                            size="sm"
                            className="h-6 px-2 text-xs"
                          >
                            <List className="w-3 h-3 mr-1" />
                            {showResponseDataTables[index] ? 'Show Sample' : 'Show Data'}
                          </Button>
                        )}
                      </div>
                      {!showResponseDataTables[index] ? (
                        <div className="p-3 bg-grey-100">
                          <pre className="text-xs font-mono overflow-x-auto text-grey">
                            {(() => {
                              try {
                                const sample = response.body?.sample || response.body;
                                if (typeof sample === 'string') {
                                  try {
                                    const parsed = JSON.parse(sample);
                                    return JSON.stringify(parsed, null, 2);
                                  } catch {
                                    return sample;
                                  }
                                }
                                return JSON.stringify(sample, null, 2);
                              } catch {
                                return response.body?.sample || response.body;
                              }
                            })()}
                          </pre>
                        </div>
                      ) : (
                        <div className="p-3">
                          <Table className="text-xs">
                            <TableHeader>
                              <TableRow className="bg-grey-100">
                                <TableHead className="font-semibold text-grey">Key</TableHead>
                                <TableHead className="font-semibold text-grey">Type</TableHead>
                                <TableHead className="font-semibold text-grey">Description</TableHead>
                                <TableHead className="font-semibold text-grey">Length</TableHead>
                                <TableHead className="font-semibold text-grey">Required</TableHead>
                              </TableRow>
                            </TableHeader>
                            <TableBody>
                              {response.body.data.map((field: any, fieldIndex: number) => (
                                <TableRow key={fieldIndex}>
                                  <TableCell className="font-mono text-grey">{field.key}</TableCell>
                                  <TableCell>
                                    <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                                      {field.type || 'string'}
                                    </span>
                                  </TableCell>
                                  <TableCell className="text-grey">{field.description || '-'}</TableCell>
                                  <TableCell className="text-grey text-xs">
                                    {field.minLength || field.maxLength ? (
                                      <span>
                                        {field.minLength && `min: ${field.minLength}`}
                                        {field.minLength && field.maxLength && ', '}
                                        {field.maxLength && `max: ${field.maxLength}`}
                                      </span>
                                    ) : '-'}
                                  </TableCell>
                                  <TableCell>
                                    <span className={cn(
                                      'px-2 py-0.5 rounded text-xs font-medium',
                                      field.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey'
                                    )}>
                                      {field.required ? 'Yes' : 'No'}
                                    </span>
                                  </TableCell>
                                </TableRow>
                              ))}
                            </TableBody>
                          </Table>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Code Sidebar */}
      {showCodeSidebar && (
        <CodeSidebar
          title={formData.name || action.tag || 'Action'}
          subtitle={`App: ${app?.app_name || 'Unknown'}`}
          tag={formData.tag}
          onClose={() => setShowCodeSidebar(false)}
          generateCodeSections={generateCodeSections}
          environments={customEnvs.map(env => ({
            slug: env.slug,
            env_name: environments.find((e: any) => e.slug === env.slug)?.env_name || env.slug
          }))}
          onSectionAction={(sectionTitle) => {
            if (sectionTitle === 'Input') {
              return (
                <button
                  onClick={handleSetDefaultValues}
                  className={`px-3 py-1.5 text-xs rounded transition-colors h-7 ${
                    showDefaultValuesForm
                      ? 'bg-white border border-red text-red hover:bg-red/10'
                      : 'bg-primary hover:bg-primary/90 text-white'
                  }`}
                >
                  {showDefaultValuesForm ? 'X' : 'Set Values'}
                </button>
              );
            }
            return null;
          }}
          sectionFooter={(sectionTitle) => {
            if (sectionTitle === 'Input' && showDefaultValuesForm) {
              return (
                <div className="mb-3 p-3 border border-grey-300 rounded bg-grey-50">
                  <h4 className="text-sm font-medium mb-3">Default Values</h4>
                  {defaultValues.map((defaultValue, idx) => (
                    <div key={idx} className="flex gap-2 mb-2 items-end">
                      <div className="flex-1">
                        <Label className="text-xs">Variable</Label>
                        <Select
                          value={defaultValue.variable}
                          onValueChange={(value) => updateDefaultValue(idx, 'variable', value)}
                        >
                          <SelectTrigger className="h-8">
                            <SelectValue placeholder="Select variable" />
                          </SelectTrigger>
                          <SelectContent>
                            {availableVariables.map(variable => (
                              <SelectItem key={variable.value} value={variable.value}>
                                {variable.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>

                      <div className="flex-1">
                        <Label className="text-xs">Value Source</Label>
                        <Select
                          value={defaultValue.valueSource}
                          onValueChange={(value) => updateDefaultValue(idx, 'valueSource', value)}
                          disabled={!defaultValue.variable}
                        >
                          <SelectTrigger className="h-8">
                            <SelectValue placeholder="Select source" />
                          </SelectTrigger>
                          <SelectContent>
                            {availableValueSources.map(source => (
                              <SelectItem key={source.value} value={source.value}>
                                {source.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>

                      <div className="flex-1">
                        <Label className="text-xs">Value</Label>
                        {defaultValue.valueSource === 'default' ? (
                          <Input
                            value="$Default"
                            disabled
                            className="h-8 bg-grey-100"
                          />
                        ) : (
                          <Input
                            value={defaultValue.value}
                            onChange={(e) => updateDefaultValue(idx, 'value', e.target.value)}
                            placeholder="Enter value"
                            className="h-8"
                            disabled={!defaultValue.valueSource}
                          />
                        )}
                      </div>

                      <button
                        type="button"
                        onClick={() => removeDefaultValue(idx)}
                        className="h-8 px-2 bg-red hover:bg-red/80 text-white text-xs rounded transition-colors"
                      >
                        Remove
                      </button>
                    </div>
                  ))}
                  <button
                    type="button"
                    onClick={addDefaultValue}
                    className="mt-2 px-3 py-1 bg-grey hover:bg-grey/80 text-white text-xs rounded transition-colors"
                  >
                    Add Default Value
                  </button>
                </div>
              );
            }
            return null;
          }}
        />
      )}

      {/* Environment Modal */}
      <Dialog open={showEnvModal} onOpenChange={setShowEnvModal}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="text-grey flex items-center gap-2">
              <Globe className="h-5 w-5 text-primary" />
              {environments.find((e: any) => e.slug === selectedEnvForModal?.slug)?.env_name || selectedEnvForModal?.slug}
            </DialogTitle>
            <DialogDescription>
              Configure the base URL for this environment
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="env-base-url">Base URL</Label>
              <Input
                id="env-base-url"
                placeholder="https://api.example.com"
                value={editedEnvBaseUrl}
                onChange={(e) => setEditedEnvBaseUrl(e.target.value)}
                className="font-mono"
              />
            </div>

            {selectedEnvForModal && (
              <div className="flex items-center gap-2 text-sm text-grey-600">
                <span>Status:</span>
                <span className={cn(
                  'px-2 py-0.5 rounded text-xs font-medium',
                  selectedEnvForModal.active
                    ? 'bg-green/10 text-green'
                    : 'bg-grey-100 text-grey-600'
                )}>
                  {selectedEnvForModal.active ? 'Active' : 'Inactive'}
                </span>
              </div>
            )}
          </div>

          <DialogFooter className="gap-2">
            <Button
              variant="outline"
              onClick={() => {
                setShowEnvModal(false);
                setSelectedEnvForModal(null);
              }}
            >
              Cancel
            </Button>
            {selectedEnvForModal && !selectedEnvForModal.active && (
              <Button
                variant="outline"
                onClick={handleSelectEnvFromModal}
                className="text-primary border-primary hover:bg-primary/10"
              >
                Use This Environment
              </Button>
            )}
            <Button onClick={handleSaveEnvChanges}>
              Save Changes
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
