import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Send, Plus, Trash2, Code, Globe, Hash, FileCode, Server, RotateCcw, BookOpen, X, List } from 'lucide-react';
import toast from 'react-hot-toast';
import { cn } from '@/lib/utils';
import { useAuth } from '@/store/useAuth';
import { reconstructPayloadFromSample, reconstructActionPayload } from '@/utils/payloadReconstruction';

interface ActionViewTabContentProps {
  action: any;
}

interface KeyValue {
  key: string;
  value: string;
  description?: string;
  enabled: boolean;
}

interface ICustomEnv {
  slug: string;
  base_url: string;
  config?: Record<string, unknown>;
  active: boolean;
}

// Helper function to syntax highlight JSON
const syntaxHighlightJSON = (jsonString: any) => {
  try {
    const obj = typeof jsonString === 'string' ? JSON.parse(jsonString) : jsonString;
    const formatted = JSON.stringify(obj, null, 2);

    return formatted.replace(
      /("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g,
      (match) => {
        let cls = 'text-purple-600'; // numbers
        if (/^"/.test(match)) {
          if (/:$/.test(match)) {
            cls = 'text-blue-600 font-semibold'; // keys
          } else {
            cls = 'text-green-700'; // string values
          }
        } else if (/true|false/.test(match)) {
          cls = 'text-orange-600'; // boolean
        } else if (/null/.test(match)) {
          cls = 'text-red-600'; // null
        }
        return `<span class="${cls}">${match}</span>`;
      }
    );
  } catch (e) {
    return typeof jsonString === 'string' ? jsonString : JSON.stringify(jsonString, null, 2);
  }
};

export default function ActionViewTabContent({ action }: ActionViewTabContentProps) {
  const { user } = useAuth();

  // Debug logging
  console.log('ActionViewTabContent - action data:', action);
  console.log('ActionViewTabContent - environments from action:', action.envs);
  console.log('ActionViewTabContent - action.appName:', action.appName);
  console.log('ActionViewTabContent - action.appTag:', action.appTag);

  // Form state matching the action data
  const [formData, setFormData] = useState({
    name: action.name || action.tag || '',
    tag: action.tag || '',
    description: action.description || '',
    method: action.method || 'GET',
    request_type: 'JSON',
  });

  const handleNameChange = (value: string) => {
    // Auto-generate description only if description is empty or was auto-generated
    const shouldAutoGenerateDescription =
      !formData.description ||
      formData.description === `Action for ${formData.name}`;

    setFormData({
      ...formData,
      name: value,
      description: shouldAutoGenerateDescription
        ? (value ? `Action for ${value}` : '')
        : formData.description
    });
  };

  const [fullUrl, setFullUrl] = useState('');
  const [baseUrl, setBaseUrl] = useState('');
  const [resource, setResource] = useState(action.resource || '');
  const [params, setParams] = useState<KeyValue[]>([]);
  const [query, setQuery] = useState<KeyValue[]>([]);
  const [headers, setHeaders] = useState<KeyValue[]>([
    { key: 'Content-Type', value: 'application/json', enabled: true }
  ]);
  const [body, setBody] = useState('');
  const [response, setResponse] = useState<any>(null);
  const [isLoadingRequest, setIsLoadingRequest] = useState(false);
  const [activeTab, setActiveTab] = useState('params');

  // Custom envs that will be saved with the action (ICustomEnv[])
  const [customEnvs, setCustomEnvs] = useState<ICustomEnv[]>([]);

  // State to track which CustomEnv is being updated for highlighting
  const [updatingEnvSlugs, setUpdatingEnvSlugs] = useState<Set<string>>(new Set());

  // Documentation sidebar state
  const [showDocsSidebar, setShowDocsSidebar] = useState<boolean>(false);
  const [selectedActionForDocs, setSelectedActionForDocs] = useState<any>(null);
  const [showBodyDataTable, setShowBodyDataTable] = useState<boolean>(false);
  const [showResponseDataTables, setShowResponseDataTables] = useState<Record<number, boolean>>({});

  // Code sidebar state
  const [showCodeSidebar, setShowCodeSidebar] = useState<boolean>(false);
  const [selectedLanguage, setSelectedLanguage] = useState<string>('javascript');

  // Use app data passed from parent component
  const app = {
    app_name: action.appName,
    tag: action.appTag,
    logo: action.appLogo,
    status: action.appStatus,
  };
  
  // Use environments passed from parent component
  const environments = action.envs || [];
  
  // Debug logging
  console.log('ActionViewTabContent - app data:', app);
  console.log('ActionViewTabContent - environments:', environments);

  // Initialize form data from action
  useEffect(() => {
    if (action) {
      setFormData({
        name: action.name || action.tag || '',
        tag: action.tag || '',
        description: action.description || '',
        method: action.method || 'GET',
        request_type: 'JSON',
      });
      setResource(action.resource || '');
    }
  }, [action]);

  // Initialize customEnvs from app environments
  useEffect(() => {
    if (environments.length > 0 && customEnvs.length === 0) {
      const envs = environments.map((env: any) => ({
        slug: env.slug,
        base_url: env.base_url || '',
        active: env.active || false,
      }));
      setCustomEnvs(envs);
      
      // Set the active environment's base URL
      const activeEnv = environments.find((env: any) => env.active) || environments[0];
      if (activeEnv?.base_url) {
        setBaseUrl(activeEnv.base_url);
      }
    }
  }, [environments]);

  // Initialize params, query, headers from action data
  useEffect(() => {
    if (action) {
      // Initialize params (only simple types, arrays/objects are handled via reconstruction)
      if (action.params?.data) {
        const simpleParams = action.params.data.filter((param: any) => {
          const fieldType = param.type?.toLowerCase() || '';
          return fieldType !== 'array' &&
                 !fieldType.startsWith('array') &&
                 fieldType !== 'object' &&
                 fieldType !== 'json';
        });

        setParams(
          simpleParams.map((param: any) => ({
            key: param.key || '',
            value: param.default || param.defaultValue || '',
            description: param.description || '',
            enabled: true,
          }))
        );
      }

      // Initialize query (only simple types, arrays/objects are handled via reconstruction)
      if (action.query?.data) {
        const simpleQuery = action.query.data.filter((param: any) => {
          const fieldType = param.type?.toLowerCase() || '';
          return fieldType !== 'array' &&
                 !fieldType.startsWith('array') &&
                 fieldType !== 'object' &&
                 fieldType !== 'json';
        });

        setQuery(
          simpleQuery.map((param: any) => ({
            key: param.key || '',
            value: param.default || param.defaultValue || '',
            description: param.description || '',
            enabled: true,
          }))
        );
      }

      // Initialize headers (only simple types, arrays/objects are handled via reconstruction)
      if (action.headers?.data) {
        const simpleHeaders = action.headers.data.filter((header: any) => {
          const fieldType = header.type?.toLowerCase() || '';
          return fieldType !== 'array' &&
                 !fieldType.startsWith('array') &&
                 fieldType !== 'object' &&
                 fieldType !== 'json';
        });

        setHeaders([
          { key: 'Content-Type', value: 'application/json', enabled: true },
          ...simpleHeaders.map((header: any) => ({
            key: header.key || '',
            value: header.default || header.defaultValue || '',
            description: header.description || '',
            enabled: true,
          }))
        ]);
      }

      // Initialize body with reconstruction from sample data
      if (action.body) {
        let bodyContent: any = {};

        // Try to use the parsed data structure first (IParsedSample array)
        if (action.body.data && Array.isArray(action.body.data) && action.body.data.length > 0) {
          // Reconstruct the full body structure using sample data
          // The reconstruction function will use sampleValue from IParsedSample
          // and handle nested objects/arrays properly
          bodyContent = reconstructPayloadFromSample(
            action.body.data,
            {} // Empty user inputs - let it use sample values
          );
        }
        // Fallback to using the raw sample if data is not available
        else if (action.body.sample) {
          try {
            // If sample is a string, parse it
            bodyContent = typeof action.body.sample === 'string'
              ? JSON.parse(action.body.sample)
              : action.body.sample;
          } catch (e) {
            // If parsing fails, use as-is or empty object
            bodyContent = action.body.sample || {};
          }
        }

        setBody(JSON.stringify(bodyContent, null, 2));
      }
    }
  }, [action]);

  // Build full URL from base URL and resource
  useEffect(() => {
    if (baseUrl && resource) {
      try {
        // Ensure resource starts with / if it doesn't already
        const normalizedResource = resource.startsWith('/') ? resource : `/${resource}`;
        const url = new URL(normalizedResource, baseUrl);
        setFullUrl(url.toString());
      } catch (e) {
        // If URL construction fails, try simple concatenation
        const normalizedResource = resource.startsWith('/') ? resource : `/${resource}`;
        setFullUrl(`${baseUrl}${normalizedResource}`);
      }
    } else if (baseUrl) {
      // If only base URL is available, show it
      setFullUrl(baseUrl);
    } else if (resource) {
      // If only resource is available, show it
      setFullUrl(resource);
    }
  }, [baseUrl, resource]);

  // Auto-update all custom envs when base URL changes (not matching any existing env)
  useEffect(() => {
    if (baseUrl && customEnvs.length > 0) {
      const matchingEnv = customEnvs.find(e => e.base_url === baseUrl);

      // If base URL doesn't match any env, update all envs to this new base URL
      if (!matchingEnv) {
        // Highlight all envs being updated
        const envSlugs = customEnvs.map(env => env.slug);
        setUpdatingEnvSlugs(new Set(envSlugs));
        
        setCustomEnvs(prev => prev.map(env => ({
          ...env,
          base_url: baseUrl
        })));
        
        // Remove highlighting after a short delay
        setTimeout(() => {
          setUpdatingEnvSlugs(new Set());
        }, 1000);
      }
    }
  }, [baseUrl]);

  const handleEnvSelect = (slug: string) => {
    // Highlight the env being updated
    setUpdatingEnvSlugs(prev => new Set(prev).add(slug));
    
    const env = customEnvs.find(e => e.slug === slug);
    if (env?.base_url) {
      setBaseUrl(env.base_url);
    }
    // Set this env as active
    setCustomEnvs(prev => prev.map(e => ({
      ...e,
      active: e.slug === slug
    })));
    
    // Remove highlighting after a short delay
    setTimeout(() => {
      setUpdatingEnvSlugs(prev => {
        const newSet = new Set(prev);
        newSet.delete(slug);
        return newSet;
      });
    }, 1000);
  };

  const handleResetEnv = (slug: string) => {
    // Highlight the env being reset
    setUpdatingEnvSlugs(prev => new Set(prev).add(slug));
    
    const originalEnv = environments.find((e: any) => e.slug === slug);
    if (originalEnv) {
      setCustomEnvs(prev => prev.map(env => {
        if (env.slug === slug) {
          return {
            ...env,
            base_url: originalEnv.base_url || '',
          };
        }
        return env;
      }));

      // If this is the active env, update the main base URL too
      const env = customEnvs.find(e => e.slug === slug && e.active);
      if (env) {
        setBaseUrl(originalEnv.base_url || '');
      }

      toast.success('Environment reset to default');
      
      // Remove highlighting after a short delay
      setTimeout(() => {
        setUpdatingEnvSlugs(prev => {
          const newSet = new Set(prev);
          newSet.delete(slug);
          return newSet;
        });
      }, 1000);
    }
  };

  const addKeyValue = (
    setter: React.Dispatch<React.SetStateAction<KeyValue[]>>
  ) => {
    setter(prev => [...prev, { key: '', value: '', enabled: true }]);
  };

  const updateKeyValue = (
    index: number,
    field: keyof KeyValue,
    value: any,
    setter: React.Dispatch<React.SetStateAction<KeyValue[]>>
  ) => {
    setter(prev => {
      const updated = [...prev];
      updated[index] = { ...updated[index], [field]: value };
      return updated;
    });
  };

  const removeKeyValue = (
    index: number,
    setter: React.Dispatch<React.SetStateAction<KeyValue[]>>
  ) => {
    setter(prev => prev.filter((_, i) => i !== index));
  };

  const handleTest = async () => {
    if (!fullUrl) {
      toast.error('Please enter a valid URL');
      return;
    }

    setIsLoadingRequest(true);
    try {
      // Collect simple user inputs from UI
      const userQueryParams: Record<string, string> = {};
      query
        .filter((q) => q.enabled && q.key)
        .forEach((q) => {
          userQueryParams[q.key] = q.value;
        });

      const userHeaders: Record<string, string> = {};
      headers
        .filter((h) => h.enabled && h.key)
        .forEach((h) => {
          userHeaders[h.key] = h.value;
        });

      const userPathParams: Record<string, string> = {};
      params
        .filter((p) => p.enabled && p.key)
        .forEach((p) => {
          userPathParams[p.key] = p.value;
        });

      // Parse body
      let userBodyData: any = {};
      if (['POST', 'PUT', 'PATCH'].includes(formData.method) && body) {
        try {
          userBodyData = JSON.parse(body);
        } catch {
          userBodyData = body; // Keep as string if not valid JSON
        }
      }

      // Reconstruct the full payload using sample data from action
      // This merges simple user inputs with complex structures (arrays/objects) from samples
      const reconstructed = reconstructActionPayload(
        {
          params: action?.params,
          body: action?.body,
          query: action?.query,
          headers: action?.headers,
        },
        {
          params: userPathParams,
          body: userBodyData,
          query: userQueryParams,
          headers: userHeaders,
        }
      );

      const queryParams = reconstructed.query || userQueryParams;
      const requestHeaders = reconstructed.headers || userHeaders;
      const pathParams = reconstructed.params || userPathParams;
      const parsedBody = reconstructed.body || userBodyData;

      // Call backend proxy
      const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || 'https://api.ductape.app/';
      const proxyUrl = `${apiBaseUrl}apps/v1/test-action`;

      const res = await fetch(proxyUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${user?.auth_token}`,
          'x-user-id': user?._id || '',
          'x-workspace-id': '',
        },
        body: JSON.stringify({
          url: fullUrl,
          method: formData.method,
          headers: requestHeaders,
          query: Object.keys(queryParams).length > 0 ? queryParams : undefined,
          params: Object.keys(pathParams).length > 0 ? pathParams : undefined,
          body: parsedBody,
        }),
      });

      const responseData = await res.json();

      // Extract metadata and actual response data
      const { _meta, data: actualData } = responseData;

      if (res.ok) {
        setResponse({
          status: _meta?.status || res.status,
          statusText: _meta?.statusText || res.statusText,
          headers: _meta?.headers || {},
          data: actualData, // The actual API response (can be array or object)
          time: _meta?.time,
          size: _meta?.size,
        });
        toast.success('Request completed');
      } else {
        // Handle error response
        setResponse({
          status: _meta?.status || res.status,
          statusText: _meta?.statusText || res.statusText,
          headers: _meta?.headers || {},
          data: actualData, // The actual API error response
          error: _meta?.error || 'Request failed',
          time: _meta?.time,
          size: _meta?.size,
        });
        toast.error(_meta?.error || 'Request failed');
      }

      setActiveTab('response'); // Auto-switch to response tab
    } catch (error: any) {
      toast.error(`Request failed: ${error.message}`);
      setResponse({
        error: error.message,
        status: 0,
        statusText: 'Network Error',
      });
      setActiveTab('response'); // Auto-switch to response tab even on error
    } finally {
      setIsLoadingRequest(false);
    }
  };


  const getMethodColor = (method: string) => {
    switch (method) {
      case 'GET':
        return 'bg-green/10 text-green';
      case 'POST':
        return 'bg-blue/10 text-blue';
      case 'PUT':
        return 'bg-orange-500/10 text-orange-500';
      case 'PATCH':
        return 'bg-purple-500/10 text-purple-500';
      case 'DELETE':
        return 'bg-red/10 text-red';
      default:
        return 'bg-grey-400 text-grey';
    }
  };

  // Generate SDK code examples
  const generateCodeExample = (language: string) => {
    const appTag = action.appTag || 'your-app-tag';
    const actionTag = formData.tag || action.tag || 'action-tag';
    const activeEnv = customEnvs.find(e => e.active);
    const envSlug = activeEnv?.slug || 'production';

    // Build parameters object
    const paramsObj: any = {};
    params.filter(p => p.enabled && p.key).forEach(p => {
      paramsObj[p.key] = p.value || `{{${p.key}}}`;
    });

    // Build query object
    const queryObj: any = {};
    query.filter(q => q.enabled && q.key).forEach(q => {
      queryObj[q.key] = q.value || `{{${q.key}}}`;
    });

    // Build headers object
    const headersObj: any = {};
    headers.filter(h => h.enabled && h.key).forEach(h => {
      headersObj[h.key] = h.value || `{{${h.key}}}`;
    });

    // Build body object
    let bodyObj: any = null;
    if (['POST', 'PUT', 'PATCH'].includes(formData.method) && body) {
      try {
        bodyObj = JSON.parse(body);
      } catch {
        bodyObj = body;
      }
    }

    switch (language) {
      case 'javascript':
        return `// Initialize Ductape SDK
const ductape = new Ductape({
  workspace_id: 'your-workspace-id',
  user_id: 'your-user-id',
  token: 'your-auth-token',
  public_key: 'your-public-key',
  type: 'product'
});

// Initialize product
await ductape.init('your-product-tag');

// Call action
const response = await ductape.apps.run({
  app_tag: '${appTag}',
  action_tag: '${actionTag}',
  env: '${envSlug}',${Object.keys(paramsObj).length > 0 ? `\n  params: ${JSON.stringify(paramsObj, null, 2).split('\n').join('\n  ')},` : ''}${Object.keys(queryObj).length > 0 ? `\n  query: ${JSON.stringify(queryObj, null, 2).split('\n').join('\n  ')},` : ''}${Object.keys(headersObj).length > 0 ? `\n  headers: ${JSON.stringify(headersObj, null, 2).split('\n').join('\n  ')},` : ''}${bodyObj ? `\n  body: ${JSON.stringify(bodyObj, null, 2).split('\n').join('\n  ')}` : ''}
});

console.log(response.data);`;

      case 'python':
        return `# Initialize Ductape SDK
from ductape import Ductape

ductape = Ductape(
    workspace_id='your-workspace-id',
    user_id='your-user-id',
    token='your-auth-token',
    public_key='your-public-key',
    type='product'
)

# Initialize product
ductape.init('your-product-tag')

# Call action
response = ductape.apps.run(
    app_tag='${appTag}',
    action_tag='${actionTag}',
    env='${envSlug}',${Object.keys(paramsObj).length > 0 ? `\n    params=${JSON.stringify(paramsObj, null, 4).replace(/"/g, "'")}` : ''}${Object.keys(queryObj).length > 0 ? `\n    query=${JSON.stringify(queryObj, null, 4).replace(/"/g, "'")}` : ''}${Object.keys(headersObj).length > 0 ? `\n    headers=${JSON.stringify(headersObj, null, 4).replace(/"/g, "'")}` : ''}${bodyObj ? `\n    body=${JSON.stringify(bodyObj, null, 4).replace(/"/g, "'")}` : ''}
)

print(response.data)`;

      case 'curl':
        const curlHeaders = Object.entries(headersObj).map(([k, v]) => `-H "${k}: ${v}"`).join(' \\\n  ');
        const curlUrl = `${baseUrl || 'https://api.ductape.app'}${resource}${Object.keys(queryObj).length > 0 ? '?' + new URLSearchParams(queryObj).toString() : ''}`;
        return `# Direct API call using curl
curl -X ${formData.method} "${curlUrl}" \\
  -H "Authorization: Bearer YOUR_AUTH_TOKEN" \\${curlHeaders ? '\n  ' + curlHeaders : ''}${bodyObj ? `\n  -d '${JSON.stringify(bodyObj)}'` : ''}`;

      case 'typescript':
        return `// Initialize Ductape SDK (TypeScript)
import { Ductape } from '@ductape/sdk';

const ductape = new Ductape({
  workspace_id: 'your-workspace-id',
  user_id: 'your-user-id',
  token: 'your-auth-token',
  public_key: 'your-public-key',
  type: 'product'
});

// Initialize product
await ductape.init('your-product-tag');

// Call action
const response = await ductape.apps.run({
  app_tag: '${appTag}',
  action_tag: '${actionTag}',
  env: '${envSlug}',${Object.keys(paramsObj).length > 0 ? `\n  params: ${JSON.stringify(paramsObj, null, 2).split('\n').join('\n  ')},` : ''}${Object.keys(queryObj).length > 0 ? `\n  query: ${JSON.stringify(queryObj, null, 2).split('\n').join('\n  ')},` : ''}${Object.keys(headersObj).length > 0 ? `\n  headers: ${JSON.stringify(headersObj, null, 2).split('\n').join('\n  ')},` : ''}${bodyObj ? `\n  body: ${JSON.stringify(bodyObj, null, 2).split('\n').join('\n  ')}` : ''}
});

console.log(response.data);`;

      default:
        return '// Select a language to see code examples';
    }
  };

  return (
    <div className="h-full overflow-hidden bg-grey-100 flex flex-col lg:flex-row relative">
      {/* Left Panel - URL & Environments */}
      <div className="w-full lg:w-2/5 border-b lg:border-b-0 lg:border-r border-grey-400 bg-white overflow-auto">
        <div className="p-4 lg:p-6 space-y-4 lg:space-y-6">
          {/* Header */}
          <div className="space-y-3 lg:space-y-4">
            <div className="flex items-center gap-2 lg:gap-3">
              <div className="w-10 h-10 lg:w-12 lg:h-12 rounded-lg bg-blue/10 flex items-center justify-center flex-shrink-0">
                <Globe className="h-5 w-5 lg:h-6 lg:w-6 text-blue" />
              </div>
              <div className="flex-1">
                <Input
                  placeholder="Action Name"
                  value={formData.name}
                  onChange={(e) => handleNameChange(e.target.value)}
                  className="text-lg lg:text-xl font-bold border-none p-0 h-auto focus-visible:ring-0"
                />
              </div>
              <div className="flex gap-2">
                <Button
                  onClick={() => {
                    setSelectedActionForDocs(action);
                    setShowDocsSidebar(true);
                    setShowCodeSidebar(false);
                  }}
                  size="sm"
                  variant="outline"
                  className="h-8 px-3 text-xs"
                >
                  <BookOpen className="w-3 h-3 mr-1" />
                  View Docs
                </Button>
                <Button
                  onClick={() => {
                    setShowCodeSidebar(true);
                    setShowDocsSidebar(false);
                  }}
                  size="sm"
                  variant="outline"
                  className="h-8 px-3 text-xs"
                >
                  <Code className="w-3 h-3 mr-1" />
                  Code
                </Button>
              </div>
            </div>

            <div className="text-xs text-grey-600 bg-grey-100 px-3 py-1.5 rounded inline-block">
              Tag: <span className="font-mono">{formData.tag || 'auto-generated'}</span>
            </div>

            <Textarea
              placeholder="Description (optional)"
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              className="text-sm resize-none"
              rows={2}
            />
          </div>

          {/* App Information */}
          {app && (
            <div className="pt-4 border-t border-grey-400">
              <Label className="text-sm font-semibold text-grey flex items-center gap-2 mb-3">
                <Server className="h-4 w-4 text-primary" />
                App Context
              </Label>
              
              <div className="p-3 bg-grey-100 rounded-lg border border-grey-400">
                <div className="flex items-center gap-3">
                  {/* App Logo */}
                  <div className="w-10 h-10 rounded-lg bg-green/10 flex items-center justify-center text-green text-sm font-semibold flex-shrink-0">
                    {app?.logo ? (
                      <img
                        src={app?.logo}
                        alt={app?.app_name}
                        className="w-full h-full rounded-lg object-cover"
                      />
                    ) : (
                      app?.app_name?.split(' ')
                        .map((word: string) => word[0])
                        .join('')
                        .toUpperCase()
                        .slice(0, 2)
                    )}
                  </div>
                  
                  {/* App Info */}
                  <div className="flex-1 min-w-0">
                    <h4 className="text-sm font-medium text-grey truncate">
                      {app?.app_name}
                    </h4>
                    <p className="text-xs text-grey-600 truncate">
                      {app?.tag}
                    </p>
                    {app?.status && (
                      <span className={cn(
                        'inline-flex items-center px-2 py-0.5 rounded text-xs font-medium mt-1',
                        app?.status === 'active' 
                          ? 'bg-green/10 text-green' 
                          : 'bg-grey-400 text-grey-600'
                      )}>
                        {app?.status}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* URL Builder */}
          <div className="space-y-3 pt-4 border-t border-grey-400">
            <Label className="text-sm font-semibold text-grey">Request URL</Label>

            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
              <Select
                value={formData.method}
                onValueChange={(value) => setFormData(prev => ({ ...prev, method: value }))}
              >
                <SelectTrigger className="w-full sm:w-28">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map(method => (
                    <SelectItem key={method} value={method}>
                      <span className={cn('px-2 py-1 rounded text-xs font-bold', getMethodColor(method))}>
                        {method}
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>

              <Button
                onClick={handleTest}
                disabled={isLoadingRequest || !fullUrl || !baseUrl}
                className="bg-primary text-white hover:bg-primary/90 w-full sm:w-auto"
                size="sm"
              >
                <Send className="h-4 w-4 mr-1" />
                {isLoadingRequest ? 'Sending...' : 'Send'}
              </Button>
            </div>

            <Input
              placeholder={baseUrl ? "Select an environment to see full URL" : "No environment selected"}
              value={fullUrl}
              readOnly
              className="font-mono text-sm bg-grey-50"
            />
            
            {!baseUrl && (
              <div className="text-xs text-amber-600 bg-amber-50 border border-amber-200 rounded px-3 py-2">
                ⚠️ Please select an environment above to enable the Send button
              </div>
            )}
            
            <div className="p-3 bg-grey-100 rounded-lg border border-grey-400">
              <Label className="text-xs font-medium text-grey-600 mb-2 flex items-center gap-2">
                <Hash className="h-3 w-3" />
                Resource Path
              </Label>
              <Input
                placeholder="/api/v1/endpoint"
                value={resource}
                onChange={(e) => setResource(e.target.value)}
                className="font-mono text-xs h-8"
              />
              <p className="text-xs text-grey-500 mt-1">
                {baseUrl ? `Full URL: ${baseUrl}${resource.startsWith('/') ? resource : `/${resource}`}` : 'Select an environment to see full URL'}
              </p>
            </div>

          </div>

          {/* Environments */}
          {environments.length > 0 && (
            <div className="pt-4 border-t border-grey-400">
              <Label className="text-sm font-semibold text-grey flex items-center gap-2 mb-3">
                <Server className="h-4 w-4 text-primary" />
                Environments
              </Label>

              <div className="space-y-2">
                {customEnvs.map((env) => {
                  const originalEnv = environments.find((e: any) => e.slug === env.slug);
                  const isModified = env.base_url !== originalEnv?.base_url;
                  const isUpdating = updatingEnvSlugs.has(env.slug);

                  return (
                    <div key={env.slug} className="space-y-2">
                      <div className="flex items-center justify-between">
                        <button
                          onClick={() => handleEnvSelect(env.slug)}
                          className={cn(
                            'flex items-center gap-2 px-3 py-2 rounded text-sm font-medium transition-all duration-300 flex-1',
                            isUpdating && 'animate-pulse ring-4 ring-yellow-400 ring-opacity-75 shadow-lg',
                            env.active
                              ? isUpdating 
                                ? 'bg-yellow-400 text-yellow-900 shadow-xl transform scale-105'
                                : 'bg-primary text-white'
                              : isUpdating
                                ? 'bg-yellow-200 text-yellow-900 shadow-xl transform scale-105'
                                : 'bg-grey-100 text-grey-700 hover:bg-grey-200'
                          )}
                        >
                          <span>{originalEnv?.env_name || env.slug}</span>
                          {isModified && !isUpdating && (
                            <span className="w-1.5 h-1.5 rounded-full bg-orange-500" title="Modified" />
                          )}
                          {isUpdating && (
                            <span className="w-2 h-2 rounded-full bg-yellow-600 animate-ping" title="Updating..." />
                          )}
                        </button>

                        {isModified && !isUpdating && (
                          <Button
                            onClick={() => handleResetEnv(env.slug)}
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2"
                            title="Reset to default"
                          >
                            <RotateCcw className="h-3 w-3" />
                          </Button>
                        )}
                      </div>

                      {env.active && (
                        <div className="pl-3 text-xs text-grey-600">
                          <code className={cn(
                            "px-2 py-1 rounded border block transition-all duration-300",
                            isUpdating 
                              ? "bg-yellow-100 border-yellow-400 text-yellow-800 shadow-md"
                              : "bg-grey-100 border-grey-400"
                          )}>
                            {env.base_url || 'Not set'}
                          </code>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Right Panel - Request/Response */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
          <div className="border-b border-grey-400 bg-white px-4 lg:px-6">
            <TabsList className="w-full justify-start rounded-none bg-transparent p-0 h-auto overflow-x-auto">
              <TabsTrigger
                value="params"
                className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-3 lg:px-4 py-3 text-sm lg:text-base whitespace-nowrap"
              >
                Params
              </TabsTrigger>
              <TabsTrigger
                value="headers"
                className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-3 lg:px-4 py-3 text-sm lg:text-base whitespace-nowrap"
              >
                Headers
              </TabsTrigger>
              {['POST', 'PUT', 'PATCH'].includes(formData.method) && (
                <TabsTrigger
                  value="body"
                  className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-3 lg:px-4 py-3 text-sm lg:text-base whitespace-nowrap"
                >
                  Body
                </TabsTrigger>
              )}
              <TabsTrigger
                value="response"
                className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-3 lg:px-4 py-3 text-sm lg:text-base whitespace-nowrap"
                disabled={!response}
              >
                Response
              </TabsTrigger>
            </TabsList>
          </div>

          <div className="flex-1 overflow-auto">
            <TabsContent value="params" className="p-4 lg:p-6 space-y-6 m-0">
              {/* Query Parameters Section */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Label className="text-base font-semibold text-grey flex items-center gap-2">
                    <Hash className="h-4 w-4 text-primary" />
                    Query Parameters
                  </Label>
                  <Button onClick={() => addKeyValue(setQuery)} variant="outline" size="sm">
                    <Plus className="h-4 w-4 mr-2" />
                    Add Query
                  </Button>
                </div>
                <div className="space-y-2">
                  {query.length === 0 ? (
                    <p className="text-sm text-grey-600 text-center py-8 bg-grey-100 rounded-lg border border-grey-400">
                      No query parameters
                    </p>
                  ) : (
                    query.map((item, index) => (
                      <div key={index} className="flex flex-col sm:flex-row gap-2 items-stretch sm:items-center p-2 bg-grey-100 rounded border border-grey-400">
                        <div className="flex items-center gap-2">
                          <input
                            type="checkbox"
                            checked={item.enabled}
                            onChange={(e) => updateKeyValue(index, 'enabled', e.target.checked, setQuery)}
                            className="w-4 h-4 rounded border-grey-400"
                          />
                          <Button
                            onClick={() => removeKeyValue(index, setQuery)}
                            variant="ghost"
                            size="sm"
                            className="h-9 w-9 p-0 text-red-600 hover:text-red-700 hover:bg-red-50 flex-shrink-0"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                        <Input
                          placeholder="Key"
                          value={item.key}
                          onChange={(e) => updateKeyValue(index, 'key', e.target.value, setQuery)}
                          className="flex-1 h-9"
                        />
                        <Input
                          placeholder="Value"
                          value={item.value}
                          onChange={(e) => updateKeyValue(index, 'value', e.target.value, setQuery)}
                          className="flex-1 h-9"
                        />
                      </div>
                    ))
                  )}
                </div>
              </div>

              {/* Divider */}
              <div className="border-t border-grey-400"></div>

              {/* Path Parameters Section */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Label className="text-base font-semibold text-grey flex items-center gap-2">
                    <Hash className="h-4 w-4 text-primary" />
                    Path Parameters
                  </Label>
                  <Button onClick={() => addKeyValue(setParams)} variant="outline" size="sm">
                    <Plus className="h-4 w-4 mr-2" />
                    Add Path
                  </Button>
                </div>
                <div className="space-y-2">
                  {params.length === 0 ? (
                    <p className="text-sm text-grey-600 text-center py-8 bg-grey-100 rounded-lg border border-grey-400">
                      No path parameters
                    </p>
                  ) : (
                    params.map((item, index) => (
                      <div key={index} className="flex flex-col sm:flex-row gap-2 items-stretch sm:items-center p-2 bg-grey-100 rounded border border-grey-400">
                        <div className="flex items-center gap-2">
                          <input
                            type="checkbox"
                            checked={item.enabled}
                            onChange={(e) => updateKeyValue(index, 'enabled', e.target.checked, setParams)}
                            className="w-4 h-4 rounded border-grey-400"
                          />
                          <Button
                            onClick={() => removeKeyValue(index, setParams)}
                            variant="ghost"
                            size="sm"
                            className="h-9 w-9 p-0 text-red-600 hover:text-red-700 hover:bg-red-50 flex-shrink-0"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                        <Input
                          placeholder="Key"
                          value={item.key}
                          onChange={(e) => updateKeyValue(index, 'key', e.target.value, setParams)}
                          className="flex-1 h-9"
                        />
                        <Input
                          placeholder="Value"
                          value={item.value}
                          onChange={(e) => updateKeyValue(index, 'value', e.target.value, setParams)}
                          className="flex-1 h-9"
                        />
                      </div>
                    ))
                  )}
                </div>
              </div>
            </TabsContent>

            <TabsContent value="headers" className="p-4 lg:p-6 space-y-4 m-0">
              <div className="flex items-center justify-between">
                <Label className="text-base font-semibold text-grey flex items-center gap-2">
                  <Code className="h-4 w-4 text-primary" />
                  Headers
                </Label>
                <Button onClick={() => addKeyValue(setHeaders)} variant="outline" size="sm">
                  <Plus className="h-4 w-4 mr-2" />
                  Add
                </Button>
              </div>
              <div className="space-y-2">
                {headers.length === 0 ? (
                  <p className="text-sm text-grey-600 text-center py-8 bg-grey-100 rounded-lg">
                    No headers
                  </p>
                ) : (
                  headers.map((item, index) => (
                    <div key={index} className="flex flex-col sm:flex-row gap-2 items-stretch sm:items-center p-2 bg-grey-100 rounded border border-grey-400">
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={item.enabled}
                          onChange={(e) => updateKeyValue(index, 'enabled', e.target.checked, setHeaders)}
                          className="w-4 h-4 rounded border-grey-400"
                        />
                        <Button
                          onClick={() => removeKeyValue(index, setHeaders)}
                          variant="ghost"
                          size="sm"
                          className="h-9 w-9 p-0 text-red-600 hover:text-red-700 hover:bg-red-50 flex-shrink-0"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                      <Input
                        placeholder="Key"
                        value={item.key}
                        onChange={(e) => updateKeyValue(index, 'key', e.target.value, setHeaders)}
                        className="flex-1 h-9"
                      />
                      <Input
                        placeholder="Value"
                        value={item.value}
                        onChange={(e) => updateKeyValue(index, 'value', e.target.value, setHeaders)}
                        className="flex-1 h-9"
                      />
                    </div>
                  ))
                )}
              </div>
            </TabsContent>

            {['POST', 'PUT', 'PATCH'].includes(formData.method) && (
              <TabsContent value="body" className="p-4 lg:p-6 space-y-4 m-0">
                <Label className="text-base font-semibold text-grey flex items-center gap-2">
                  <FileCode className="h-4 w-4 text-primary" />
                  Request Body
                </Label>
                <Textarea
                  placeholder='{\n  "key": "value"\n}'
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  className="font-mono text-sm min-h-[600px]"
                />
              </TabsContent>
            )}

            <TabsContent value="response" className="m-0 h-full flex flex-col overflow-hidden">
              {!response ? (
                <div className="flex items-center justify-center h-full text-grey-600">
                  <div className="text-center">
                    <p className="text-lg mb-2">No response yet</p>
                    <p className="text-sm">Send a request to see the response</p>
                  </div>
                </div>
              ) : (
                <div className="h-full flex flex-col overflow-hidden">
                  {response.status && (
                    <div className="flex-shrink-0 flex items-center gap-2 p-3 mx-6 mt-6 bg-grey-100 rounded-lg border border-grey-400">
                      <span className="text-sm font-medium text-grey-600">Status:</span>
                      <span className={cn(
                        'px-3 py-1 rounded text-xs font-bold',
                        response.status >= 200 && response.status < 300
                          ? 'bg-green/10 text-green border border-green/20'
                          : response.status >= 400
                          ? 'bg-red/10 text-red border border-red/20'
                          : 'bg-grey-400 text-grey'
                      )}>
                        {response.status} {response.statusText}
                      </span>
                      {response.time !== undefined && (
                        <>
                          <span className="text-grey-300 mx-2">|</span>
                          <span className="text-sm font-medium text-grey-600">Time:</span>
                          <span className="text-sm text-grey-700">{response.time}ms</span>
                        </>
                      )}
                      {response.size !== undefined && (
                        <>
                          <span className="text-grey-300 mx-2">|</span>
                          <span className="text-sm font-medium text-grey-600">Size:</span>
                          <span className="text-sm text-grey-700">{response.size} bytes</span>
                        </>
                      )}
                    </div>
                  )}
                  <div className="flex-1 flex flex-col min-h-0 px-6 pb-6 pt-4">
                    <div className="flex items-center justify-between mb-2 flex-shrink-0">
                      <Label className="text-sm font-medium text-grey-600">Response Body</Label>
                      <Button
                        onClick={() => {
                          try {
                            const jsonString = JSON.stringify(response.data || response, null, 2);
                            navigator.clipboard.writeText(jsonString);
                            toast.success('Response copied to clipboard');
                          } catch (e) {
                            toast.error('Failed to copy response');
                          }
                        }}
                        variant="outline"
                        size="sm"
                        className="gap-2"
                      >
                        <Code className="h-4 w-4" />
                        Copy
                      </Button>
                    </div>
                    <div className="flex-1 bg-white rounded-lg border border-grey-400 p-4 overflow-auto font-mono text-sm min-h-0 max-h-[700px]">
                      <pre
                        className="text-grey-800"
                        style={{
                          whiteSpace: 'pre-wrap',
                          wordBreak: 'break-word',
                        }}
                        dangerouslySetInnerHTML={{
                          __html: syntaxHighlightJSON(response.data || response)
                        }}
                      />
                    </div>
                  </div>
                </div>
              )}
            </TabsContent>
          </div>
        </Tabs>
      </div>

      {/* Documentation Sidebar */}
      {showDocsSidebar && selectedActionForDocs && (
        <div className="fixed top-0 right-0 h-full w-[500px] bg-white shadow-2xl border-l border-grey-300 z-50 overflow-y-auto">
          <div className="sticky top-0 bg-white border-b border-grey-300 p-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-grey flex items-center gap-2">
              <BookOpen className="w-5 h-5" />
              Action Documentation
            </h3>
            <Button
              onClick={() => {
                setShowDocsSidebar(false);
                setSelectedActionForDocs(null);
              }}
              variant="ghost"
              size="sm"
            >
              <X className="w-4 h-4" />
            </Button>
          </div>

          <div className="p-4 space-y-6">
            {/* Action Details */}
            <div>
              <h4 className="text-lg font-bold text-grey mb-2">{selectedActionForDocs.name || selectedActionForDocs.tag}</h4>
              {selectedActionForDocs.tag && (
                <span className="text-xs px-2 py-1 bg-primary/15 text-primary rounded font-mono">
                  {selectedActionForDocs.tag}
                </span>
              )}
            </div>

            {/* Method */}
            {selectedActionForDocs.method && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-1 block">Method</Label>
                <span className={cn(
                  'px-3 py-1 rounded text-xs font-bold inline-block',
                  selectedActionForDocs.method === 'GET' && 'bg-green/10 text-green',
                  selectedActionForDocs.method === 'POST' && 'bg-blue/10 text-blue',
                  selectedActionForDocs.method === 'PUT' && 'bg-orange-500/10 text-orange-500',
                  selectedActionForDocs.method === 'PATCH' && 'bg-purple-500/10 text-purple-500',
                  selectedActionForDocs.method === 'DELETE' && 'bg-red/10 text-red',
                )}>
                  {selectedActionForDocs.method}
                </span>
              </div>
            )}

            {/* Description */}
            {selectedActionForDocs.description && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-1 block">Description</Label>
                <p className="text-sm text-grey-600">{selectedActionForDocs.description}</p>
              </div>
            )}

            {/* Endpoint/Resource */}
            {selectedActionForDocs.resource && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-1 block">Endpoint</Label>
                <code className="text-xs bg-grey-100 px-2 py-1 rounded border border-grey-300 font-mono block overflow-x-auto">
                  {selectedActionForDocs.resource}
                </code>
              </div>
            )}

            {/* Request Type */}
            {selectedActionForDocs.request_type && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-1 block">Request Type</Label>
                <span className="text-xs px-2 py-1 bg-grey-100 text-grey-700 rounded border border-grey-300">
                  {selectedActionForDocs.request_type}
                </span>
              </div>
            )}

            {/* Path Parameters */}
            {selectedActionForDocs.params?.data && selectedActionForDocs.params.data.length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-2 block">Path Parameters</Label>
                <div className="border border-grey-300 rounded overflow-hidden">
                  <Table className="text-xs">
                    <TableHeader>
                      <TableRow className="bg-grey-100">
                        <TableHead className="font-semibold">Key</TableHead>
                        <TableHead className="font-semibold">Type</TableHead>
                        <TableHead className="font-semibold">Description</TableHead>
                        <TableHead className="font-semibold">Required</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {selectedActionForDocs.params.data.map((param: any, index: number) => (
                        <TableRow key={index}>
                          <TableCell className="font-mono">{param.key}</TableCell>
                          <TableCell>
                            <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                              {param.type || 'string'}
                            </span>
                          </TableCell>
                          <TableCell className="text-grey-600">{param.description || '-'}</TableCell>
                          <TableCell>
                            <span className={cn(
                              'px-2 py-0.5 rounded text-xs font-medium',
                              param.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey-600'
                            )}>
                              {param.required ? 'Yes' : 'No'}
                            </span>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            {/* Query Parameters */}
            {selectedActionForDocs.query?.data && selectedActionForDocs.query.data.length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-2 block">Query Parameters</Label>
                <div className="border border-grey-300 rounded overflow-hidden">
                  <Table className="text-xs">
                    <TableHeader>
                      <TableRow className="bg-grey-100">
                        <TableHead className="font-semibold">Key</TableHead>
                        <TableHead className="font-semibold">Type</TableHead>
                        <TableHead className="font-semibold">Description</TableHead>
                        <TableHead className="font-semibold">Required</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {selectedActionForDocs.query.data.map((param: any, index: number) => (
                        <TableRow key={index}>
                          <TableCell className="font-mono">{param.key}</TableCell>
                          <TableCell>
                            <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                              {param.type || 'string'}
                            </span>
                          </TableCell>
                          <TableCell className="text-grey-600">{param.description || '-'}</TableCell>
                          <TableCell>
                            <span className={cn(
                              'px-2 py-0.5 rounded text-xs font-medium',
                              param.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey-600'
                            )}>
                              {param.required ? 'Yes' : 'No'}
                            </span>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            {/* Headers */}
            {selectedActionForDocs.headers?.data && selectedActionForDocs.headers.data.length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-2 block">Headers</Label>
                <div className="border border-grey-300 rounded overflow-hidden">
                  <Table className="text-xs">
                    <TableHeader>
                      <TableRow className="bg-grey-100">
                        <TableHead className="font-semibold">Key</TableHead>
                        <TableHead className="font-semibold">Description</TableHead>
                        <TableHead className="font-semibold">Required</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {selectedActionForDocs.headers.data.map((header: any, index: number) => (
                        <TableRow key={index}>
                          <TableCell className="font-mono">{header.key}</TableCell>
                          <TableCell className="text-grey-600">{header.description || '-'}</TableCell>
                          <TableCell>
                            <span className={cn(
                              'px-2 py-0.5 rounded text-xs font-medium',
                              header.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey-600'
                            )}>
                              {header.required ? 'Yes' : 'No'}
                            </span>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            {/* Request Body */}
            {selectedActionForDocs.body?.sample && (
              <div>
                <div className="flex items-center justify-between mb-2">
                  <Label className="text-sm font-semibold text-grey-700">Request Body</Label>
                  {selectedActionForDocs.body?.data && selectedActionForDocs.body.data.length > 0 && (
                    <Button
                      onClick={() => setShowBodyDataTable(!showBodyDataTable)}
                      variant="outline"
                      size="sm"
                      className="h-7 px-2 text-xs"
                    >
                      <List className="w-3 h-3 mr-1" />
                      {showBodyDataTable ? 'Show Sample' : 'Show Data'}
                    </Button>
                  )}
                </div>
                {!showBodyDataTable ? (
                  <div className="bg-grey-50 rounded border border-grey-300 p-3">
                    <pre className="text-xs font-mono overflow-x-auto">
                      {(() => {
                        try {
                          const sample = selectedActionForDocs.body.sample;
                          if (typeof sample === 'string') {
                            try {
                              const parsed = JSON.parse(sample);
                              return JSON.stringify(parsed, null, 2);
                            } catch {
                              return sample;
                            }
                          }
                          return JSON.stringify(sample, null, 2);
                        } catch {
                          return selectedActionForDocs.body.sample;
                        }
                      })()}
                    </pre>
                  </div>
                ) : (
                  <div className="border border-grey-300 rounded overflow-hidden">
                    <Table className="text-xs">
                      <TableHeader>
                        <TableRow className="bg-grey-100">
                          <TableHead className="font-semibold">Key</TableHead>
                          <TableHead className="font-semibold">Type</TableHead>
                          <TableHead className="font-semibold">Description</TableHead>
                          <TableHead className="font-semibold">Length</TableHead>
                          <TableHead className="font-semibold">Required</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {selectedActionForDocs.body.data.map((field: any, index: number) => (
                          <TableRow key={index}>
                            <TableCell className="font-mono">{field.key}</TableCell>
                            <TableCell>
                              <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                                {field.type || 'string'}
                              </span>
                            </TableCell>
                            <TableCell className="text-grey-600">{field.description || '-'}</TableCell>
                            <TableCell className="text-grey-600 text-xs">
                              {field.minLength || field.maxLength ? (
                                <span>
                                  {field.minLength && `min: ${field.minLength}`}
                                  {field.minLength && field.maxLength && ', '}
                                  {field.maxLength && `max: ${field.maxLength}`}
                                </span>
                              ) : '-'}
                            </TableCell>
                            <TableCell>
                              <span className={cn(
                                'px-2 py-0.5 rounded text-xs font-medium',
                                field.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey-600'
                              )}>
                                {field.required ? 'Yes' : 'No'}
                              </span>
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                )}
              </div>
            )}

            {/* Responses */}
            {selectedActionForDocs.responses && selectedActionForDocs.responses.filter((r: any) => r.success === true).length > 0 && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-2 block">Responses</Label>
                <div className="space-y-3">
                  {selectedActionForDocs.responses.filter((r: any) => r.success === true).map((response: any, index: number) => (
                    <div key={index} className="border border-grey-300 rounded-lg overflow-hidden">
                      <div className="bg-grey-100 px-3 py-2 flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className={cn(
                            'px-2 py-1 rounded text-xs font-medium',
                            response.status >= 200 && response.status < 300 ? 'bg-green/10 text-green' : 'bg-grey-100 text-grey-600'
                          )}>
                            {response.status}
                          </span>
                          <span className="text-xs text-grey-600">{response.message || 'Success'}</span>
                        </div>
                        {response.body?.data && response.body.data.length > 0 && (
                          <Button
                            onClick={() => setShowResponseDataTables(prev => ({ ...prev, [index]: !prev[index] }))}
                            variant="outline"
                            size="sm"
                            className="h-6 px-2 text-xs"
                          >
                            <List className="w-3 h-3 mr-1" />
                            {showResponseDataTables[index] ? 'Show Sample' : 'Show Data'}
                          </Button>
                        )}
                      </div>
                      {!showResponseDataTables[index] ? (
                        <div className="p-3 bg-grey-50">
                          <pre className="text-xs font-mono overflow-x-auto">
                            {(() => {
                              try {
                                const sample = response.body?.sample || response.body;
                                if (typeof sample === 'string') {
                                  try {
                                    const parsed = JSON.parse(sample);
                                    return JSON.stringify(parsed, null, 2);
                                  } catch {
                                    return sample;
                                  }
                                }
                                return JSON.stringify(sample, null, 2);
                              } catch {
                                return response.body?.sample || response.body;
                              }
                            })()}
                          </pre>
                        </div>
                      ) : (
                        <div className="p-3">
                          <Table className="text-xs">
                            <TableHeader>
                              <TableRow className="bg-grey-100">
                                <TableHead className="font-semibold">Key</TableHead>
                                <TableHead className="font-semibold">Type</TableHead>
                                <TableHead className="font-semibold">Description</TableHead>
                                <TableHead className="font-semibold">Length</TableHead>
                                <TableHead className="font-semibold">Required</TableHead>
                              </TableRow>
                            </TableHeader>
                            <TableBody>
                              {response.body.data.map((field: any, fieldIndex: number) => (
                                <TableRow key={fieldIndex}>
                                  <TableCell className="font-mono">{field.key}</TableCell>
                                  <TableCell>
                                    <span className="px-2 py-0.5 bg-blue/10 text-blue rounded text-xs">
                                      {field.type || 'string'}
                                    </span>
                                  </TableCell>
                                  <TableCell className="text-grey-600">{field.description || '-'}</TableCell>
                                  <TableCell className="text-grey-600 text-xs">
                                    {field.minLength || field.maxLength ? (
                                      <span>
                                        {field.minLength && `min: ${field.minLength}`}
                                        {field.minLength && field.maxLength && ', '}
                                        {field.maxLength && `max: ${field.maxLength}`}
                                      </span>
                                    ) : '-'}
                                  </TableCell>
                                  <TableCell>
                                    <span className={cn(
                                      'px-2 py-0.5 rounded text-xs font-medium',
                                      field.required ? 'bg-red/10 text-red' : 'bg-grey-100 text-grey-600'
                                    )}>
                                      {field.required ? 'Yes' : 'No'}
                                    </span>
                                  </TableCell>
                                </TableRow>
                              ))}
                            </TableBody>
                          </Table>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Code Sidebar */}
      {showCodeSidebar && (
        <div className="fixed top-0 right-0 h-full w-[600px] bg-white shadow-2xl border-l border-grey-300 z-50 overflow-y-auto">
          <div className="sticky top-0 bg-white border-b border-grey-300 p-4 flex items-center justify-between">
            <h3 className="text-lg font-semibold text-grey flex items-center gap-2">
              <Code className="w-5 h-5" />
              Code Examples
            </h3>
            <Button
              onClick={() => setShowCodeSidebar(false)}
              variant="ghost"
              size="sm"
            >
              <X className="w-4 h-4" />
            </Button>
          </div>

          <div className="p-4 space-y-6">
            {/* Action Details */}
            <div>
              <h4 className="text-lg font-bold text-grey mb-2">{formData.name || action.tag}</h4>
              {formData.tag && (
                <span className="text-xs px-2 py-1 bg-primary/15 text-primary rounded font-mono">
                  {formData.tag}
                </span>
              )}
              {app?.app_name && (
                <p className="text-sm text-grey-600 mt-2">
                  App: <span className="font-medium">{app.app_name}</span>
                </p>
              )}
            </div>

            {/* Language Selector */}
            <div>
              <Label className="text-sm font-semibold text-grey-700 mb-2 block">Language</Label>
              <Select value={selectedLanguage} onValueChange={setSelectedLanguage}>
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="javascript">JavaScript</SelectItem>
                  <SelectItem value="typescript">TypeScript</SelectItem>
                  <SelectItem value="python">Python</SelectItem>
                  <SelectItem value="curl">cURL</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Code Example */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <Label className="text-sm font-semibold text-grey-700">Example Code</Label>
                <Button
                  onClick={() => {
                    navigator.clipboard.writeText(generateCodeExample(selectedLanguage));
                    toast.success('Code copied to clipboard');
                  }}
                  variant="outline"
                  size="sm"
                  className="gap-2"
                >
                  <Code className="h-4 w-4" />
                  Copy
                </Button>
              </div>
              <pre className="bg-grey-50 p-4 rounded-lg border border-grey-300 text-sm overflow-x-auto font-mono">
                <code>{generateCodeExample(selectedLanguage)}</code>
              </pre>
            </div>

            {/* Installation Instructions */}
            {(selectedLanguage === 'javascript' || selectedLanguage === 'typescript') && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-2 block">Installation</Label>
                <pre className="bg-grey-50 p-4 rounded-lg border border-grey-300 text-sm font-mono">
                  <code>npm install @ductape/sdk</code>
                </pre>
              </div>
            )}

            {selectedLanguage === 'python' && (
              <div>
                <Label className="text-sm font-semibold text-grey-700 mb-2 block">Installation</Label>
                <pre className="bg-grey-50 p-4 rounded-lg border border-grey-300 text-sm font-mono">
                  <code>pip install ductape</code>
                </pre>
              </div>
            )}

            {/* Usage Notes */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h5 className="text-sm font-semibold text-blue-900 mb-2">Usage Notes</h5>
              <ul className="text-xs text-blue-800 space-y-1">
                <li>• Replace placeholder values with your actual credentials</li>
                <li>• Ensure you have the required permissions to access this action</li>
                <li>• The response data will be available in the <code className="bg-blue-100 px-1 rounded">response.data</code> property</li>
                {selectedLanguage === 'curl' && (
                  <li>• For production use, consider using the SDK instead of direct API calls</li>
                )}
              </ul>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
