server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /boot-loader.js {
    try_files $uri =404;
    default_type text/javascript;
  }

  location = /boot-loader.css {
    try_files $uri =404;
    default_type text/css;
  }

  location /assets/ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public, immutable";
  }
}
