export type TabType =
  | 'request'
  | 'app'
  | 'product'
  | 'storage'
  | 'session'
  | 'session-activity'
  | 'session-dashboard'
  | 'session-user'
  | 'cache'
  | 'cache-values'
  | 'healthcheck'
  | 'database'
  | 'graph'
  | 'vector'
  | 'feature'
  | 'feature-run'
  | 'resilience-invocation'
  | 'agent'
  | 'agent-run'
  | 'message-broker'
  | 'message-broker-events'
  | 'notification'
  | 'notification-explorer'
  | 'new-notification'
  | 'notification-template'
  | 'message'
  | 'new-message'
  | 'new-topic'
  | 'fallback'
  | 'new-fallback'
  | 'quota'
  | 'new-quota'
  | 'job'
  | 'job-run'
  | 'job-explorer'
  | 'new-healthcheck'
  | 'webhook'
  | 'webhook-explorer'
  | 'auth'
  | 'logs'
  | 'dashboard'
  | 'tokens'
  | 'teams'
  | 'partnership'
  | 'brief'
  | 'marketplace'
  | 'notifier'
  | 'pricing'
  | 'settings'
  | 'cloud';

export interface Tab {
  id: string;
  type: TabType;
  title: string;
  itemId?: string; // ID of the actual item (e.g., product_id, app_id)
  data?: any; // Additional data specific to the tab type
  isDirty?: boolean; // Has unsaved changes
}
